<?php

namespace Database\Seeders;

use App\Models\Commune;
use Illuminate\Database\Seeder;

class CommuneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $communes = [
            ["name" => "Adrar", "wilaya_id" => "1"],
            ["name" => "Tamest", "wilaya_id" => "1"],
            ["name" => "Charouine", "wilaya_id" => "1"],
            ["name" => "Reggane", "wilaya_id" => "1"],
            ["name" => "Inozghmir", "wilaya_id" => "1"],
            ["name" => "Tit", "wilaya_id" => "1"],
            ["name" => "Ksar Kaddour", "wilaya_id" => "1"],
            ["name" => "Tsabit", "wilaya_id" => "1"],
            ["name" => "Timimoun", "wilaya_id" => "1"],
            ["name" => "Ouled Said", "wilaya_id" => "1"],
            ["name" => "Zaouiet Kounta", "wilaya_id" => "1"],
            ["name" => "Aoulef", "wilaya_id" => "1"],
            ["name" => "Timokten", "wilaya_id" => "1"],
            ["name" => "Tamentit", "wilaya_id" => "1"],
            ["name" => "Fenoughil", "wilaya_id" => "1"],
            ["name" => "Tinerkouk", "wilaya_id" => "1"],
            ["name" => "Deldoul", "wilaya_id" => "1"],
            ["name" => "Sali", "wilaya_id" => "1"],
            ["name" => "Akabli", "wilaya_id" => "1"],
            ["name" => "Metarfa", "wilaya_id" => "1"],
            ["name" => "O Ahmed Timmi", "wilaya_id" => "1"],
            ["name" => "Bouda", "wilaya_id" => "1"],
            ["name" => "Aougrout", "wilaya_id" => "1"],
            ["name" => "Talmine", "wilaya_id" => "1"],
            ["name" => "B Badji Mokhtar", "wilaya_id" => "1"],
            ["name" => "Sbaa", "wilaya_id" => "1"],
            ["name" => "Ouled Aissa", "wilaya_id" => "1"],
            ["name" => "Timiaouine", "wilaya_id" => "1"],
            ["name" => "Chlef", "wilaya_id" => "2"],
            ["name" => "Tenes", "wilaya_id" => "2"],
            ["name" => "Benairia", "wilaya_id" => "2"],
            ["name" => "El Karimia", "wilaya_id" => "2"],
            ["name" => "Tadjna", "wilaya_id" => "2"],
            ["name" => "Taougrite", "wilaya_id" => "2"],
            ["name" => "Beni Haoua", "wilaya_id" => "2"],
            ["name" => "Sobha", "wilaya_id" => "2"],
            ["name" => "Harchoun", "wilaya_id" => "2"],
            ["name" => "Ouled Fares", "wilaya_id" => "2"],
            ["name" => "Sidi Akacha", "wilaya_id" => "2"],
            ["name" => "Boukadir", "wilaya_id" => "2"],
            ["name" => "Beni Rached", "wilaya_id" => "2"],
            ["name" => "Talassa", "wilaya_id" => "2"],
            ["name" => "Herenfa", "wilaya_id" => "2"],
            ["name" => "Oued Goussine", "wilaya_id" => "2"],
            ["name" => "Dahra", "wilaya_id" => "2"],
            ["name" => "Ouled Abbes", "wilaya_id" => "2"],
            ["name" => "Sendjas", "wilaya_id" => "2"],
            ["name" => "Zeboudja", "wilaya_id" => "2"],
            ["name" => "Oued Sly", "wilaya_id" => "2"],
            ["name" => "Abou El Hassen", "wilaya_id" => "2"],
            ["name" => "El Marsa", "wilaya_id" => "2"],
            ["name" => "Chettia", "wilaya_id" => "2"],
            ["name" => "Sidi Abderrahmane", "wilaya_id" => "2"],
            ["name" => "Moussadek", "wilaya_id" => "2"],
            ["name" => "El Hadjadj", "wilaya_id" => "2"],
            ["name" => "Labiod Medjadja", "wilaya_id" => "2"],
            ["name" => "Oued Fodda", "wilaya_id" => "2"],
            ["name" => "Ouled Ben Abdelkader", "wilaya_id" => "2"],
            ["name" => "Bouzghaia", "wilaya_id" => "2"],
            ["name" => "Ain Merane", "wilaya_id" => "2"],
            ["name" => "Oum Drou", "wilaya_id" => "2"],
            ["name" => "Breira", "wilaya_id" => "2"],
            ["name" => "Ben Boutaleb", "wilaya_id" => "2"],
            ["name" => "Laghouat", "wilaya_id" => "3"],
            ["name" => "Ksar El Hirane", "wilaya_id" => "3"],
            ["name" => "Benacer Ben Chohra", "wilaya_id" => "3"],
            ["name" => "Sidi Makhlouf", "wilaya_id" => "3"],
            ["name" => "Hassi Delaa", "wilaya_id" => "3"],
            ["name" => "Hassi R Mel", "wilaya_id" => "3"],
            ["name" => "Ain Mahdi", "wilaya_id" => "3"],
            ["name" => "Tadjmout", "wilaya_id" => "3"],
            ["name" => "Kheneg", "wilaya_id" => "3"],
            ["name" => "Gueltat Sidi Saad", "wilaya_id" => "3"],
            ["name" => "Ain Sidi Ali", "wilaya_id" => "3"],
            ["name" => "Beidha", "wilaya_id" => "3"],
            ["name" => "Brida", "wilaya_id" => "3"],
            ["name" => "El Ghicha", "wilaya_id" => "3"],
            ["name" => "Hadj Mechri", "wilaya_id" => "3"],
            ["name" => "Sebgag", "wilaya_id" => "3"],
            ["name" => "Taouiala", "wilaya_id" => "3"],
            ["name" => "Tadjrouna", "wilaya_id" => "3"],
            ["name" => "Aflou", "wilaya_id" => "3"],
            ["name" => "El Assafia", "wilaya_id" => "3"],
            ["name" => "Oued Morra", "wilaya_id" => "3"],
            ["name" => "Oued M Zi", "wilaya_id" => "3"],
            ["name" => "El Haouaita", "wilaya_id" => "3"],
            ["name" => "Sidi Bouzid", "wilaya_id" => "3"],
            ["name" => "Oum El Bouaghi", "wilaya_id" => "4"],
            ["name" => "Ain Beida", "wilaya_id" => "4"],
            ["name" => "Ainmlila", "wilaya_id" => "4"],
            ["name" => "Behir Chergui", "wilaya_id" => "4"],
            ["name" => "El Amiria", "wilaya_id" => "4"],
            ["name" => "Sigus", "wilaya_id" => "4"],
            ["name" => "El Belala", "wilaya_id" => "4"],
            ["name" => "Ain Babouche", "wilaya_id" => "4"],
            ["name" => "Berriche", "wilaya_id" => "4"],
            ["name" => "Ouled Hamla", "wilaya_id" => "4"],
            ["name" => "Dhala", "wilaya_id" => "4"],
            ["name" => "Ain Kercha", "wilaya_id" => "4"],
            ["name" => "Hanchir Toumghani", "wilaya_id" => "4"],
            ["name" => "El Djazia", "wilaya_id" => "4"],
            ["name" => "Ain Diss", "wilaya_id" => "4"],
            ["name" => "Fkirina", "wilaya_id" => "4"],
            ["name" => "Souk Naamane", "wilaya_id" => "4"],
            ["name" => "Zorg", "wilaya_id" => "4"],
            ["name" => "El Fedjoudj Boughrar", "wilaya_id" => "4"],
            ["name" => "Ouled Zouai", "wilaya_id" => "4"],
            ["name" => "Bir Chouhada", "wilaya_id" => "4"],
            ["name" => "Ksar Sbahi", "wilaya_id" => "4"],
            ["name" => "Oued Nini", "wilaya_id" => "4"],
            ["name" => "Meskiana", "wilaya_id" => "4"],
            ["name" => "Ain Fekroune", "wilaya_id" => "4"],
            ["name" => "Rahia", "wilaya_id" => "4"],
            ["name" => "Ain Zitoun", "wilaya_id" => "4"],
            ["name" => "Ouled Gacem", "wilaya_id" => "4"],
            ["name" => "El Harmilia", "wilaya_id" => "4"],
            ["name" => "Batna", "wilaya_id" => "5"],
            ["name" => "Ghassira", "wilaya_id" => "5"],
            ["name" => "Maafa", "wilaya_id" => "5"],
            ["name" => "Merouana", "wilaya_id" => "5"],
            ["name" => "Seriana", "wilaya_id" => "5"],
            ["name" => "Menaa", "wilaya_id" => "5"],
            ["name" => "El Madher", "wilaya_id" => "5"],
            ["name" => "Tazoult", "wilaya_id" => "5"],
            ["name" => "Ngaous", "wilaya_id" => "5"],
            ["name" => "Guigba", "wilaya_id" => "5"],
            ["name" => "Inoughissen", "wilaya_id" => "5"],
            ["name" => "Ouyoun El Assafir", "wilaya_id" => "5"],
            ["name" => "Djerma", "wilaya_id" => "5"],
            ["name" => "Bitam", "wilaya_id" => "5"],
            ["name" => "Metkaouak", "wilaya_id" => "5"],
            ["name" => "Arris", "wilaya_id" => "5"],
            ["name" => "Kimmel", "wilaya_id" => "5"],
            ["name" => "Tilatou", "wilaya_id" => "5"],
            ["name" => "Ain Djasser", "wilaya_id" => "5"],
            ["name" => "Ouled Selam", "wilaya_id" => "5"],
            ["name" => "Tigherghar", "wilaya_id" => "5"],
            ["name" => "Ain Yagout", "wilaya_id" => "5"],
            ["name" => "Fesdis", "wilaya_id" => "5"],
            ["name" => "Sefiane", "wilaya_id" => "5"],
            ["name" => "Rahbat", "wilaya_id" => "5"],
            ["name" => "Tighanimine", "wilaya_id" => "5"],
            ["name" => "Lemsane", "wilaya_id" => "5"],
            ["name" => "Ksar Belezma", "wilaya_id" => "5"],
            ["name" => "Seggana", "wilaya_id" => "5"],
            ["name" => "Ichmoul", "wilaya_id" => "5"],
            ["name" => "Foum Toub", "wilaya_id" => "5"],
            ["name" => "Beni Foudhala El Hakania", "wilaya_id" => "5"],
            ["name" => "Oued El Ma", "wilaya_id" => "5"],
            ["name" => "Talkhamt", "wilaya_id" => "5"],
            ["name" => "Bouzina", "wilaya_id" => "5"],
            ["name" => "Chemora", "wilaya_id" => "5"],
            ["name" => "Oued Chaaba", "wilaya_id" => "5"],
            ["name" => "Taxlent", "wilaya_id" => "5"],
            ["name" => "Gosbat", "wilaya_id" => "5"],
            ["name" => "Ouled Aouf", "wilaya_id" => "5"],
            ["name" => "Boumagueur", "wilaya_id" => "5"],
            ["name" => "Barika", "wilaya_id" => "5"],
            ["name" => "Djezzar", "wilaya_id" => "5"],
            ["name" => "Tkout", "wilaya_id" => "5"],
            ["name" => "Ain Touta", "wilaya_id" => "5"],
            ["name" => "Hidoussa", "wilaya_id" => "5"],
            ["name" => "Teniet El Abed", "wilaya_id" => "5"],
            ["name" => "Oued Taga", "wilaya_id" => "5"],
            ["name" => "Ouled Fadel", "wilaya_id" => "5"],
            ["name" => "Timgad", "wilaya_id" => "5"],
            ["name" => "Ras El Aioun", "wilaya_id" => "5"],
            ["name" => "Chir", "wilaya_id" => "5"],
            ["name" => "Ouled Si Slimane", "wilaya_id" => "5"],
            ["name" => "Zanat El Beida", "wilaya_id" => "5"],
            ["name" => "Amdoukal", "wilaya_id" => "5"],
            ["name" => "Ouled Ammar", "wilaya_id" => "5"],
            ["name" => "El Hassi", "wilaya_id" => "5"],
            ["name" => "Lazrou", "wilaya_id" => "5"],
            ["name" => "Boumia", "wilaya_id" => "5"],
            ["name" => "Boulhilat", "wilaya_id" => "5"],
            ["name" => "Larbaa", "wilaya_id" => "5"],
            ["name" => "Bejaia", "wilaya_id" => "6"],
            ["name" => "Amizour", "wilaya_id" => "6"],
            ["name" => "Ferraoun", "wilaya_id" => "6"],
            ["name" => "Taourirt Ighil", "wilaya_id" => "6"],
            ["name" => "Chelata", "wilaya_id" => "6"],
            ["name" => "Tamokra", "wilaya_id" => "6"],
            ["name" => "Timzrit", "wilaya_id" => "6"],
            ["name" => "Souk El Thenine", "wilaya_id" => "6"],
            ["name" => "Mcisna", "wilaya_id" => "6"],
            ["name" => "Thinabdher", "wilaya_id" => "6"],
            ["name" => "Tichi", "wilaya_id" => "6"],
            ["name" => "Semaoun", "wilaya_id" => "6"],
            ["name" => "Kendira", "wilaya_id" => "6"],
            ["name" => "Tifra", "wilaya_id" => "6"],
            ["name" => "Ighram", "wilaya_id" => "6"],
            ["name" => "Amalou", "wilaya_id" => "6"],
            ["name" => "Ighil Ali", "wilaya_id" => "6"],
            ["name" => "Ifelain Ilmathen", "wilaya_id" => "6"],
            ["name" => "Toudja", "wilaya_id" => "6"],
            ["name" => "Darguina", "wilaya_id" => "6"],
            ["name" => "Sidi Ayad", "wilaya_id" => "6"],
            ["name" => "Aokas", "wilaya_id" => "6"],
            ["name" => "Beni Djellil", "wilaya_id" => "6"],
            ["name" => "Adekar", "wilaya_id" => "6"],
            ["name" => "Akbou", "wilaya_id" => "6"],
            ["name" => "Seddouk", "wilaya_id" => "6"],
            ["name" => "Tazmalt", "wilaya_id" => "6"],
            ["name" => "Ait Rizine", "wilaya_id" => "6"],
            ["name" => "Chemini", "wilaya_id" => "6"],
            ["name" => "Souk Oufella", "wilaya_id" => "6"],
            ["name" => "Taskriout", "wilaya_id" => "6"],
            ["name" => "Tibane", "wilaya_id" => "6"],
            ["name" => "Tala Hamza", "wilaya_id" => "6"],
            ["name" => "Barbacha", "wilaya_id" => "6"],
            ["name" => "Beni Ksila", "wilaya_id" => "6"],
            ["name" => "Ouzallaguen", "wilaya_id" => "6"],
            ["name" => "Bouhamza", "wilaya_id" => "6"],
            ["name" => "Beni Melikeche", "wilaya_id" => "6"],
            ["name" => "Sidi Aich", "wilaya_id" => "6"],
            ["name" => "El Kseur", "wilaya_id" => "6"],
            ["name" => "Melbou", "wilaya_id" => "6"],
            ["name" => "Akfadou", "wilaya_id" => "6"],
            ["name" => "Leflaye", "wilaya_id" => "6"],
            ["name" => "Kherrata", "wilaya_id" => "6"],
            ["name" => "Draa Kaid", "wilaya_id" => "6"],
            ["name" => "Tamridjet", "wilaya_id" => "6"],
            ["name" => "Ait Smail", "wilaya_id" => "6"],
            ["name" => "Boukhelifa", "wilaya_id" => "6"],
            ["name" => "Tizi Nberber", "wilaya_id" => "6"],
            ["name" => "Beni Maouch", "wilaya_id" => "6"],
            ["name" => "Oued Ghir", "wilaya_id" => "6"],
            ["name" => "Boudjellil", "wilaya_id" => "6"],
            ["name" => "Biskra", "wilaya_id" => "7"],
            ["name" => "Oumache", "wilaya_id" => "7"],
            ["name" => "Branis", "wilaya_id" => "7"],
            ["name" => "Chetma", "wilaya_id" => "7"],
            ["name" => "Ouled Djellal", "wilaya_id" => "7"],
            ["name" => "Ras El Miaad", "wilaya_id" => "7"],
            ["name" => "Besbes", "wilaya_id" => "7"],
            ["name" => "Sidi Khaled", "wilaya_id" => "7"],
            ["name" => "Doucen", "wilaya_id" => "7"],
            ["name" => "Ech Chaiba", "wilaya_id" => "7"],
            ["name" => "Sidi Okba", "wilaya_id" => "7"],
            ["name" => "Mchouneche", "wilaya_id" => "7"],
            ["name" => "El Haouch", "wilaya_id" => "7"],
            ["name" => "Ain Naga", "wilaya_id" => "7"],
            ["name" => "Zeribet El Oued", "wilaya_id" => "7"],
            ["name" => "El Feidh", "wilaya_id" => "7"],
            ["name" => "El Kantara", "wilaya_id" => "7"],
            ["name" => "Ain Zaatout", "wilaya_id" => "7"],
            ["name" => "El Outaya", "wilaya_id" => "7"],
            ["name" => "Djemorah", "wilaya_id" => "7"],
            ["name" => "Tolga", "wilaya_id" => "7"],
            ["name" => "Lioua", "wilaya_id" => "7"],
            ["name" => "Lichana", "wilaya_id" => "7"],
            ["name" => "Ourlal", "wilaya_id" => "7"],
            ["name" => "Mlili", "wilaya_id" => "7"],
            ["name" => "Foughala", "wilaya_id" => "7"],
            ["name" => "Bordj Ben Azzouz", "wilaya_id" => "7"],
            ["name" => "Meziraa", "wilaya_id" => "7"],
            ["name" => "Bouchagroun", "wilaya_id" => "7"],
            ["name" => "Mekhadma", "wilaya_id" => "7"],
            ["name" => "El Ghrous", "wilaya_id" => "7"],
            ["name" => "El Hadjab", "wilaya_id" => "7"],
            ["name" => "Khanguet Sidinadji", "wilaya_id" => "7"],
            ["name" => "Bechar", "wilaya_id" => "8"],
            ["name" => "Erg Ferradj", "wilaya_id" => "8"],
            ["name" => "Ouled Khoudir", "wilaya_id" => "8"],
            ["name" => "Meridja", "wilaya_id" => "8"],
            ["name" => "Timoudi", "wilaya_id" => "8"],
            ["name" => "Lahmar", "wilaya_id" => "8"],
            ["name" => "Beni Abbes", "wilaya_id" => "8"],
            ["name" => "Beni Ikhlef", "wilaya_id" => "8"],
            ["name" => "Mechraa Houari B", "wilaya_id" => "8"],
            ["name" => "Kenedsa", "wilaya_id" => "8"],
            ["name" => "Igli", "wilaya_id" => "8"],
            ["name" => "Tabalbala", "wilaya_id" => "8"],
            ["name" => "Taghit", "wilaya_id" => "8"],
            ["name" => "El Ouata", "wilaya_id" => "8"],
            ["name" => "Boukais", "wilaya_id" => "8"],
            ["name" => "Mogheul", "wilaya_id" => "8"],
            ["name" => "Abadla", "wilaya_id" => "8"],
            ["name" => "Kerzaz", "wilaya_id" => "8"],
            ["name" => "Ksabi", "wilaya_id" => "8"],
            ["name" => "Tamtert", "wilaya_id" => "8"],
            ["name" => "Beni Ounif", "wilaya_id" => "8"],
            ["name" => "Blida", "wilaya_id" => "9"],
            ["name" => "Chebli", "wilaya_id" => "9"],
            ["name" => "Bouinan", "wilaya_id" => "9"],
            ["name" => "Oued El Alleug", "wilaya_id" => "9"],
            ["name" => "Ouled Yaich", "wilaya_id" => "9"],
            ["name" => "Chrea", "wilaya_id" => "9"],
            ["name" => "El Affroun", "wilaya_id" => "9"],
            ["name" => "Chiffa", "wilaya_id" => "9"],
            ["name" => "Hammam Melouane", "wilaya_id" => "9"],
            ["name" => "Ben Khlil", "wilaya_id" => "9"],
            ["name" => "Soumaa", "wilaya_id" => "9"],
            ["name" => "Mouzaia", "wilaya_id" => "9"],
            ["name" => "Souhane", "wilaya_id" => "9"],
            ["name" => "Meftah", "wilaya_id" => "9"],
            ["name" => "Ouled Selama", "wilaya_id" => "9"],
            ["name" => "Boufarik", "wilaya_id" => "9"],
            ["name" => "Larbaa", "wilaya_id" => "9"],
            ["name" => "Oued Djer", "wilaya_id" => "9"],
            ["name" => "Beni Tamou", "wilaya_id" => "9"],
            ["name" => "Bouarfa", "wilaya_id" => "9"],
            ["name" => "Beni Mered", "wilaya_id" => "9"],
            ["name" => "Bougara", "wilaya_id" => "9"],
            ["name" => "Guerrouaou", "wilaya_id" => "9"],
            ["name" => "Ain Romana", "wilaya_id" => "9"],
            ["name" => "Djebabra", "wilaya_id" => "9"],
            ["name" => "Bouira", "wilaya_id" => "10"],
            ["name" => "El Asnam", "wilaya_id" => "10"],
            ["name" => "Guerrouma", "wilaya_id" => "10"],
            ["name" => "Souk El Khemis", "wilaya_id" => "10"],
            ["name" => "Kadiria", "wilaya_id" => "10"],
            ["name" => "Hanif", "wilaya_id" => "10"],
            ["name" => "Dirah", "wilaya_id" => "10"],
            ["name" => "Ait Laaziz", "wilaya_id" => "10"],
            ["name" => "Taghzout", "wilaya_id" => "10"],
            ["name" => "Raouraoua", "wilaya_id" => "10"],
            ["name" => "Mezdour", "wilaya_id" => "10"],
            ["name" => "Haizer", "wilaya_id" => "10"],
            ["name" => "Lakhdaria", "wilaya_id" => "10"],
            ["name" => "Maala", "wilaya_id" => "10"],
            ["name" => "El Hachimia", "wilaya_id" => "10"],
            ["name" => "Aomar", "wilaya_id" => "10"],
            ["name" => "Chorfa", "wilaya_id" => "10"],
            ["name" => "Bordj Oukhriss", "wilaya_id" => "10"],
            ["name" => "El Adjiba", "wilaya_id" => "10"],
            ["name" => "El Hakimia", "wilaya_id" => "10"],
            ["name" => "El Khebouzia", "wilaya_id" => "10"],
            ["name" => "Ahl El Ksar", "wilaya_id" => "10"],
            ["name" => "Bouderbala", "wilaya_id" => "10"],
            ["name" => "Zbarbar", "wilaya_id" => "10"],
            ["name" => "Ain El Hadjar", "wilaya_id" => "10"],
            ["name" => "Djebahia", "wilaya_id" => "10"],
            ["name" => "Aghbalou", "wilaya_id" => "10"],
            ["name" => "Taguedit", "wilaya_id" => "10"],
            ["name" => "Ain Turk", "wilaya_id" => "10"],
            ["name" => "Saharidj", "wilaya_id" => "10"],
            ["name" => "Dechmia", "wilaya_id" => "10"],
            ["name" => "Ridane", "wilaya_id" => "10"],
            ["name" => "Bechloul", "wilaya_id" => "10"],
            ["name" => "Boukram", "wilaya_id" => "10"],
            ["name" => "Ain Bessam", "wilaya_id" => "10"],
            ["name" => "Bir Ghbalou", "wilaya_id" => "10"],
            ["name" => "Mchedallah", "wilaya_id" => "10"],
            ["name" => "Sour El Ghozlane", "wilaya_id" => "10"],
            ["name" => "Maamora", "wilaya_id" => "10"],
            ["name" => "Ouled Rached", "wilaya_id" => "10"],
            ["name" => "Ain Laloui", "wilaya_id" => "10"],
            ["name" => "Hadjera Zerga", "wilaya_id" => "10"],
            ["name" => "Ath Mansour", "wilaya_id" => "10"],
            ["name" => "El Mokrani", "wilaya_id" => "10"],
            ["name" => "Oued El Berdi", "wilaya_id" => "10"],
            ["name" => "Tamanghasset", "wilaya_id" => "11"],
            ["name" => "Abalessa", "wilaya_id" => "11"],
            ["name" => "In Ghar", "wilaya_id" => "11"],
            ["name" => "In Guezzam", "wilaya_id" => "11"],
            ["name" => "Idles", "wilaya_id" => "11"],
            ["name" => "Tazouk", "wilaya_id" => "11"],
            ["name" => "Tinzaouatine", "wilaya_id" => "11"],
            ["name" => "In Salah", "wilaya_id" => "11"],
            ["name" => "In Amguel", "wilaya_id" => "11"],
            ["name" => "Foggaret Ezzaouia", "wilaya_id" => "11"],
            ["name" => "Tebessa", "wilaya_id" => "12"],
            ["name" => "Bir El Ater", "wilaya_id" => "12"],
            ["name" => "Cheria", "wilaya_id" => "12"],
            ["name" => "Stah Guentis", "wilaya_id" => "12"],
            ["name" => "El Aouinet", "wilaya_id" => "12"],
            ["name" => "Lahouidjbet", "wilaya_id" => "12"],
            ["name" => "Safsaf El Ouesra", "wilaya_id" => "12"],
            ["name" => "Hammamet", "wilaya_id" => "12"],
            ["name" => "Negrine", "wilaya_id" => "12"],
            ["name" => "Bir El Mokadem", "wilaya_id" => "12"],
            ["name" => "El Kouif", "wilaya_id" => "12"],
            ["name" => "Morsott", "wilaya_id" => "12"],
            ["name" => "El Ogla", "wilaya_id" => "12"],
            ["name" => "Bir Dheheb", "wilaya_id" => "12"],
            ["name" => "El Ogla El Malha", "wilaya_id" => "12"],
            ["name" => "Gorriguer", "wilaya_id" => "12"],
            ["name" => "Bekkaria", "wilaya_id" => "12"],
            ["name" => "Boukhadra", "wilaya_id" => "12"],
            ["name" => "Ouenza", "wilaya_id" => "12"],
            ["name" => "El Ma El Biodh", "wilaya_id" => "12"],
            ["name" => "Oum Ali", "wilaya_id" => "12"],
            ["name" => "Thlidjene", "wilaya_id" => "12"],
            ["name" => "Ain Zerga", "wilaya_id" => "12"],
            ["name" => "El Meridj", "wilaya_id" => "12"],
            ["name" => "Boulhaf Dyr", "wilaya_id" => "12"],
            ["name" => "Bedjene", "wilaya_id" => "12"],
            ["name" => "El Mazeraa", "wilaya_id" => "12"],
            ["name" => "Ferkane", "wilaya_id" => "12"],
            ["name" => "Tlemcen", "wilaya_id" => "13"],
            ["name" => "Beni Mester", "wilaya_id" => "13"],
            ["name" => "Ain Tallout", "wilaya_id" => "13"],
            ["name" => "Remchi", "wilaya_id" => "13"],
            ["name" => "El Fehoul", "wilaya_id" => "13"],
            ["name" => "Sabra", "wilaya_id" => "13"],
            ["name" => "Ghazaouet", "wilaya_id" => "13"],
            ["name" => "Souani", "wilaya_id" => "13"],
            ["name" => "Djebala", "wilaya_id" => "13"],
            ["name" => "El Gor", "wilaya_id" => "13"],
            ["name" => "Oued Chouly", "wilaya_id" => "13"],
            ["name" => "Ain Fezza", "wilaya_id" => "13"],
            ["name" => "Ouled Mimoun", "wilaya_id" => "13"],
            ["name" => "Amieur", "wilaya_id" => "13"],
            ["name" => "Ain Youcef", "wilaya_id" => "13"],
            ["name" => "Zenata", "wilaya_id" => "13"],
            ["name" => "Beni Snous", "wilaya_id" => "13"],
            ["name" => "Bab El Assa", "wilaya_id" => "13"],
            ["name" => "Dar Yaghmouracene", "wilaya_id" => "13"],
            ["name" => "Fellaoucene", "wilaya_id" => "13"],
            ["name" => "Azails", "wilaya_id" => "13"],
            ["name" => "Sebbaa Chioukh", "wilaya_id" => "13"],
            ["name" => "Terni Beni Hediel", "wilaya_id" => "13"],
            ["name" => "Bensekrane", "wilaya_id" => "13"],
            ["name" => "Ain Nehala", "wilaya_id" => "13"],
            ["name" => "Hennaya", "wilaya_id" => "13"],
            ["name" => "Maghnia", "wilaya_id" => "13"],
            ["name" => "Hammam Boughrara", "wilaya_id" => "13"],
            ["name" => "Souahlia", "wilaya_id" => "13"],
            ["name" => "Msirda Fouaga", "wilaya_id" => "13"],
            ["name" => "Ain Fetah", "wilaya_id" => "13"],
            ["name" => "El Aricha", "wilaya_id" => "13"],
            ["name" => "Souk Thlata", "wilaya_id" => "13"],
            ["name" => "Sidi Abdelli", "wilaya_id" => "13"],
            ["name" => "Sebdou", "wilaya_id" => "13"],
            ["name" => "Beni Ouarsous", "wilaya_id" => "13"],
            ["name" => "Sidi Medjahed", "wilaya_id" => "13"],
            ["name" => "Beni Boussaid", "wilaya_id" => "13"],
            ["name" => "Marsa Ben Mhidi", "wilaya_id" => "13"],
            ["name" => "Nedroma", "wilaya_id" => "13"],
            ["name" => "Sidi Djillali", "wilaya_id" => "13"],
            ["name" => "Beni Bahdel", "wilaya_id" => "13"],
            ["name" => "El Bouihi", "wilaya_id" => "13"],
            ["name" => "Honaine", "wilaya_id" => "13"],
            ["name" => "Tianet", "wilaya_id" => "13"],
            ["name" => "Ouled Riyah", "wilaya_id" => "13"],
            ["name" => "Bouhlou", "wilaya_id" => "13"],
            ["name" => "Souk El Khemis", "wilaya_id" => "13"],
            ["name" => "Ain Ghoraba", "wilaya_id" => "13"],
            ["name" => "Chetouane", "wilaya_id" => "13"],
            ["name" => "Mansourah", "wilaya_id" => "13"],
            ["name" => "Beni Semiel", "wilaya_id" => "13"],
            ["name" => "Ain Kebira", "wilaya_id" => "13"],
            ["name" => "Tiaret", "wilaya_id" => "14"],
            ["name" => "Medroussa", "wilaya_id" => "14"],
            ["name" => "Ain Bouchekif", "wilaya_id" => "14"],
            ["name" => "Sidi Ali Mellal", "wilaya_id" => "14"],
            ["name" => "Ain Zarit", "wilaya_id" => "14"],
            ["name" => "Ain Deheb", "wilaya_id" => "14"],
            ["name" => "Sidi Bakhti", "wilaya_id" => "14"],
            ["name" => "Medrissa", "wilaya_id" => "14"],
            ["name" => "Zmalet El Emir Aek", "wilaya_id" => "14"],
            ["name" => "Madna", "wilaya_id" => "14"],
            ["name" => "Sebt", "wilaya_id" => "14"],
            ["name" => "Mellakou", "wilaya_id" => "14"],
            ["name" => "Dahmouni", "wilaya_id" => "14"],
            ["name" => "Rahouia", "wilaya_id" => "14"],
            ["name" => "Mahdia", "wilaya_id" => "14"],
            ["name" => "Sougueur", "wilaya_id" => "14"],
            ["name" => "Sidi Abdelghani", "wilaya_id" => "14"],
            ["name" => "Ain El Hadid", "wilaya_id" => "14"],
            ["name" => "Ouled Djerad", "wilaya_id" => "14"],
            ["name" => "Naima", "wilaya_id" => "14"],
            ["name" => "Meghila", "wilaya_id" => "14"],
            ["name" => "Guertoufa", "wilaya_id" => "14"],
            ["name" => "Sidi Hosni", "wilaya_id" => "14"],
            ["name" => "Djillali Ben Amar", "wilaya_id" => "14"],
            ["name" => "Sebaine", "wilaya_id" => "14"],
            ["name" => "Tousnina", "wilaya_id" => "14"],
            ["name" => "Frenda", "wilaya_id" => "14"],
            ["name" => "Ain Kermes", "wilaya_id" => "14"],
            ["name" => "Ksar Chellala", "wilaya_id" => "14"],
            ["name" => "Rechaiga", "wilaya_id" => "14"],
            ["name" => "Nadorah", "wilaya_id" => "14"],
            ["name" => "Tagdemt", "wilaya_id" => "14"],
            ["name" => "Oued Lilli", "wilaya_id" => "14"],
            ["name" => "Mechraa Safa", "wilaya_id" => "14"],
            ["name" => "Hamadia", "wilaya_id" => "14"],
            ["name" => "Chehaima", "wilaya_id" => "14"],
            ["name" => "Takhemaret", "wilaya_id" => "14"],
            ["name" => "Sidi Abderrahmane", "wilaya_id" => "14"],
            ["name" => "Serghine", "wilaya_id" => "14"],
            ["name" => "Bougara", "wilaya_id" => "14"],
            ["name" => "Faidja", "wilaya_id" => "14"],
            ["name" => "Tidda", "wilaya_id" => "14"],
            ["name" => "Tizi Ouzou", "wilaya_id" => "15"],
            ["name" => "Ain El Hammam", "wilaya_id" => "15"],
            ["name" => "Akbil", "wilaya_id" => "15"],
            ["name" => "Freha", "wilaya_id" => "15"],
            ["name" => "Souamaa", "wilaya_id" => "15"],
            ["name" => "Mechtrass", "wilaya_id" => "15"],
            ["name" => "Irdjen", "wilaya_id" => "15"],
            ["name" => "Timizart", "wilaya_id" => "15"],
            ["name" => "Makouda", "wilaya_id" => "15"],
            ["name" => "Draa El Mizan", "wilaya_id" => "15"],
            ["name" => "Tizi Ghenif", "wilaya_id" => "15"],
            ["name" => "Bounouh", "wilaya_id" => "15"],
            ["name" => "Ait Chaffaa", "wilaya_id" => "15"],
            ["name" => "Frikat", "wilaya_id" => "15"],
            ["name" => "Beni Aissi", "wilaya_id" => "15"],
            ["name" => "Beni Zmenzer", "wilaya_id" => "15"],
            ["name" => "Iferhounene", "wilaya_id" => "15"],
            ["name" => "Azazga", "wilaya_id" => "15"],
            ["name" => "Iloula Oumalou", "wilaya_id" => "15"],
            ["name" => "Yakouren", "wilaya_id" => "15"],
            ["name" => "Larba Nait Irathen", "wilaya_id" => "15"],
            ["name" => "Tizi Rached", "wilaya_id" => "15"],
            ["name" => "Zekri", "wilaya_id" => "15"],
            ["name" => "Ouaguenoun", "wilaya_id" => "15"],
            ["name" => "Ain Zaouia", "wilaya_id" => "15"],
            ["name" => "Mkira", "wilaya_id" => "15"],
            ["name" => "Ait Yahia", "wilaya_id" => "15"],
            ["name" => "Ait Mahmoud", "wilaya_id" => "15"],
            ["name" => "Maatka", "wilaya_id" => "15"],
            ["name" => "Ait Boumehdi", "wilaya_id" => "15"],
            ["name" => "Abi Youcef", "wilaya_id" => "15"],
            ["name" => "Beni Douala", "wilaya_id" => "15"],
            ["name" => "Illilten", "wilaya_id" => "15"],
            ["name" => "Bouzguen", "wilaya_id" => "15"],
            ["name" => "Ait Aggouacha", "wilaya_id" => "15"],
            ["name" => "Ouadhia", "wilaya_id" => "15"],
            ["name" => "Azzefoun", "wilaya_id" => "15"],
            ["name" => "Tigzirt", "wilaya_id" => "15"],
            ["name" => "Ait Aissa Mimoun", "wilaya_id" => "15"],
            ["name" => "Boghni", "wilaya_id" => "15"],
            ["name" => "Ifigha", "wilaya_id" => "15"],
            ["name" => "Ait Oumalou", "wilaya_id" => "15"],
            ["name" => "Tirmitine", "wilaya_id" => "15"],
            ["name" => "Akerrou", "wilaya_id" => "15"],
            ["name" => "Yatafen", "wilaya_id" => "15"],
            ["name" => "Beni Ziki", "wilaya_id" => "15"],
            ["name" => "Draa Ben Khedda", "wilaya_id" => "15"],
            ["name" => "Ouacif", "wilaya_id" => "15"],
            ["name" => "Idjeur", "wilaya_id" => "15"],
            ["name" => "Mekla", "wilaya_id" => "15"],
            ["name" => "Tizi Nthlata", "wilaya_id" => "15"],
            ["name" => "Beni Yenni", "wilaya_id" => "15"],
            ["name" => "Aghrib", "wilaya_id" => "15"],
            ["name" => "Iflissen", "wilaya_id" => "15"],
            ["name" => "Boudjima", "wilaya_id" => "15"],
            ["name" => "Ait Yahia Moussa", "wilaya_id" => "15"],
            ["name" => "Souk El Thenine", "wilaya_id" => "15"],
            ["name" => "Ait Khelil", "wilaya_id" => "15"],
            ["name" => "Sidi Naamane", "wilaya_id" => "15"],
            ["name" => "Iboudraren", "wilaya_id" => "15"],
            ["name" => "Aghni Goughran", "wilaya_id" => "15"],
            ["name" => "Mizrana", "wilaya_id" => "15"],
            ["name" => "Imsouhal", "wilaya_id" => "15"],
            ["name" => "Tadmait", "wilaya_id" => "15"],
            ["name" => "Ait Bouadou", "wilaya_id" => "15"],
            ["name" => "Assi Youcef", "wilaya_id" => "15"],
            ["name" => "Ait Toudert", "wilaya_id" => "15"],
            ["name" => "Alger Centre", "wilaya_id" => "16"],
            ["name" => "Sidi Mhamed", "wilaya_id" => "16"],
            ["name" => "El Madania", "wilaya_id" => "16"],
            ["name" => "Hamma Anassers", "wilaya_id" => "16"],
            ["name" => "Bab El Oued", "wilaya_id" => "16"],
            ["name" => "Bologhine Ibn Ziri", "wilaya_id" => "16"],
            ["name" => "Casbah", "wilaya_id" => "16"],
            ["name" => "Oued Koriche", "wilaya_id" => "16"],
            ["name" => "Bir Mourad Rais", "wilaya_id" => "16"],
            ["name" => "El Biar", "wilaya_id" => "16"],
            ["name" => "Bouzareah", "wilaya_id" => "16"],
            ["name" => "Birkhadem", "wilaya_id" => "16"],
            ["name" => "El Harrach", "wilaya_id" => "16"],
            ["name" => "Baraki", "wilaya_id" => "16"],
            ["name" => "Oued Smar", "wilaya_id" => "16"],
            ["name" => "Bourouba", "wilaya_id" => "16"],
            ["name" => "Hussein Dey", "wilaya_id" => "16"],
            ["name" => "Kouba", "wilaya_id" => "16"],
            ["name" => "Bachedjerah", "wilaya_id" => "16"],
            ["name" => "Dar El Beida", "wilaya_id" => "16"],
            ["name" => "Bab Azzouar", "wilaya_id" => "16"],
            ["name" => "Ben Aknoun", "wilaya_id" => "16"],
            ["name" => "Dely Ibrahim", "wilaya_id" => "16"],
            ["name" => "Bains Romains", "wilaya_id" => "16"],
            ["name" => "Rais Hamidou", "wilaya_id" => "16"],
            ["name" => "Djasr Kasentina", "wilaya_id" => "16"],
            ["name" => "El Mouradia", "wilaya_id" => "16"],
            ["name" => "Hydra", "wilaya_id" => "16"],
            ["name" => "Mohammadia", "wilaya_id" => "16"],
            ["name" => "Bordj El Kiffan", "wilaya_id" => "16"],
            ["name" => "El Magharia", "wilaya_id" => "16"],
            ["name" => "Beni Messous", "wilaya_id" => "16"],
            ["name" => "Les Eucalyptus", "wilaya_id" => "16"],
            ["name" => "Birtouta", "wilaya_id" => "16"],
            ["name" => "Tassala El Merdja", "wilaya_id" => "16"],
            ["name" => "Ouled Chebel", "wilaya_id" => "16"],
            ["name" => "Sidi Moussa", "wilaya_id" => "16"],
            ["name" => "Ain Taya", "wilaya_id" => "16"],
            ["name" => "Bordj El Bahri", "wilaya_id" => "16"],
            ["name" => "Marsa", "wilaya_id" => "16"],
            ["name" => "Haraoua", "wilaya_id" => "16"],
            ["name" => "Rouiba", "wilaya_id" => "16"],
            ["name" => "Reghaia", "wilaya_id" => "16"],
            ["name" => "Ain Benian", "wilaya_id" => "16"],
            ["name" => "Staoueli", "wilaya_id" => "16"],
            ["name" => "Zeralda", "wilaya_id" => "16"],
            ["name" => "Mahelma", "wilaya_id" => "16"],
            ["name" => "Rahmania", "wilaya_id" => "16"],
            ["name" => "Souidania", "wilaya_id" => "16"],
            ["name" => "Cheraga", "wilaya_id" => "16"],
            ["name" => "Ouled Fayet", "wilaya_id" => "16"],
            ["name" => "El Achour", "wilaya_id" => "16"],
            ["name" => "Draria", "wilaya_id" => "16"],
            ["name" => "Douera", "wilaya_id" => "16"],
            ["name" => "Baba Hassen", "wilaya_id" => "16"],
            ["name" => "Khracia", "wilaya_id" => "16"],
            ["name" => "Saoula", "wilaya_id" => "16"],
            ["name" => "Djelfa", "wilaya_id" => "17"],
            ["name" => "Moudjebara", "wilaya_id" => "17"],
            ["name" => "El Guedid", "wilaya_id" => "17"],
            ["name" => "Hassi Bahbah", "wilaya_id" => "17"],
            ["name" => "Ain Maabed", "wilaya_id" => "17"],
            ["name" => "Sed Rahal", "wilaya_id" => "17"],
            ["name" => "Feidh El Botma", "wilaya_id" => "17"],
            ["name" => "Birine", "wilaya_id" => "17"],
            ["name" => "Bouira Lahdeb", "wilaya_id" => "17"],
            ["name" => "Zaccar", "wilaya_id" => "17"],
            ["name" => "El Khemis", "wilaya_id" => "17"],
            ["name" => "Sidi Baizid", "wilaya_id" => "17"],
            ["name" => "Mliliha", "wilaya_id" => "17"],
            ["name" => "El Idrissia", "wilaya_id" => "17"],
            ["name" => "Douis", "wilaya_id" => "17"],
            ["name" => "Hassi El Euch", "wilaya_id" => "17"],
            ["name" => "Messaad", "wilaya_id" => "17"],
            ["name" => "Guettara", "wilaya_id" => "17"],
            ["name" => "Sidi Ladjel", "wilaya_id" => "17"],
            ["name" => "Had Sahary", "wilaya_id" => "17"],
            ["name" => "Guernini", "wilaya_id" => "17"],
            ["name" => "Selmana", "wilaya_id" => "17"],
            ["name" => "Ain Chouhada", "wilaya_id" => "17"],
            ["name" => "Oum Laadham", "wilaya_id" => "17"],
            ["name" => "Dar Chouikh", "wilaya_id" => "17"],
            ["name" => "Charef", "wilaya_id" => "17"],
            ["name" => "Beni Yacoub", "wilaya_id" => "17"],
            ["name" => "Zaafrane", "wilaya_id" => "17"],
            ["name" => "Deldoul", "wilaya_id" => "17"],
            ["name" => "Ain El Ibel", "wilaya_id" => "17"],
            ["name" => "Ain Oussera", "wilaya_id" => "17"],
            ["name" => "Benhar", "wilaya_id" => "17"],
            ["name" => "Hassi Fedoul", "wilaya_id" => "17"],
            ["name" => "Amourah", "wilaya_id" => "17"],
            ["name" => "Ain Fekka", "wilaya_id" => "17"],
            ["name" => "Tadmit", "wilaya_id" => "17"],
            ["name" => "Jijel", "wilaya_id" => "18"],
            ["name" => "Erraguene", "wilaya_id" => "18"],
            ["name" => "El Aouana", "wilaya_id" => "18"],
            ["name" => "Ziamma Mansouriah", "wilaya_id" => "18"],
            ["name" => "Taher", "wilaya_id" => "18"],
            ["name" => "Emir Abdelkader", "wilaya_id" => "18"],
            ["name" => "Chekfa", "wilaya_id" => "18"],
            ["name" => "Chahna", "wilaya_id" => "18"],
            ["name" => "El Milia", "wilaya_id" => "18"],
            ["name" => "Sidi Maarouf", "wilaya_id" => "18"],
            ["name" => "Settara", "wilaya_id" => "18"],
            ["name" => "El Ancer", "wilaya_id" => "18"],
            ["name" => "Sidi Abdelaziz", "wilaya_id" => "18"],
            ["name" => "Kaous", "wilaya_id" => "18"],
            ["name" => "Ghebala", "wilaya_id" => "18"],
            ["name" => "Bouraoui Belhadef", "wilaya_id" => "18"],
            ["name" => "Djmila", "wilaya_id" => "18"],
            ["name" => "Selma Benziada", "wilaya_id" => "18"],
            ["name" => "Boussif Ouled Askeur", "wilaya_id" => "18"],
            ["name" => "El Kennar Nouchfi", "wilaya_id" => "18"],
            ["name" => "Ouled Yahia Khadrouch", "wilaya_id" => "18"],
            ["name" => "Boudria Beni Yadjis", "wilaya_id" => "18"],
            ["name" => "Kemir Oued Adjoul", "wilaya_id" => "18"],
            ["name" => "Texena", "wilaya_id" => "18"],
            ["name" => "Djemaa Beni Habibi", "wilaya_id" => "18"],
            ["name" => "Bordj Taher", "wilaya_id" => "18"],
            ["name" => "Ouled Rabah", "wilaya_id" => "18"],
            ["name" => "Ouadjana", "wilaya_id" => "18"],
            ["name" => "Setif", "wilaya_id" => "19"],
            ["name" => "Ain El Kebira", "wilaya_id" => "19"],
            ["name" => "Beni Aziz", "wilaya_id" => "19"],
            ["name" => "Ouled Sidi Ahmed", "wilaya_id" => "19"],
            ["name" => "Boutaleb", "wilaya_id" => "19"],
            ["name" => "Ain Roua", "wilaya_id" => "19"],
            ["name" => "Draa Kebila", "wilaya_id" => "19"],
            ["name" => "Bir El Arch", "wilaya_id" => "19"],
            ["name" => "Beni Chebana", "wilaya_id" => "19"],
            ["name" => "Ouled Tebben", "wilaya_id" => "19"],
            ["name" => "Hamma", "wilaya_id" => "19"],
            ["name" => "Maaouia", "wilaya_id" => "19"],
            ["name" => "Ain Legraj", "wilaya_id" => "19"],
            ["name" => "Ain Abessa", "wilaya_id" => "19"],
            ["name" => "Dehamcha", "wilaya_id" => "19"],
            ["name" => "Babor", "wilaya_id" => "19"],
            ["name" => "Guidjel", "wilaya_id" => "19"],
            ["name" => "Ain Lahdjar", "wilaya_id" => "19"],
            ["name" => "Bousselam", "wilaya_id" => "19"],
            ["name" => "El Eulma", "wilaya_id" => "19"],
            ["name" => "Djemila", "wilaya_id" => "19"],
            ["name" => "Beni Ouartilane", "wilaya_id" => "19"],
            ["name" => "Rosfa", "wilaya_id" => "19"],
            ["name" => "Ouled Addouane", "wilaya_id" => "19"],
            ["name" => "Belaa", "wilaya_id" => "19"],
            ["name" => "Ain Arnat", "wilaya_id" => "19"],
            ["name" => "Amoucha", "wilaya_id" => "19"],
            ["name" => "Ain Oulmane", "wilaya_id" => "19"],
            ["name" => "Beidha Bordj", "wilaya_id" => "19"],
            ["name" => "Bouandas", "wilaya_id" => "19"],
            ["name" => "Bazer Sakhra", "wilaya_id" => "19"],
            ["name" => "Hammam Essokhna", "wilaya_id" => "19"],
            ["name" => "Mezloug", "wilaya_id" => "19"],
            ["name" => "Bir Haddada", "wilaya_id" => "19"],
            ["name" => "Serdj El Ghoul", "wilaya_id" => "19"],
            ["name" => "Harbil", "wilaya_id" => "19"],
            ["name" => "El Ouricia", "wilaya_id" => "19"],
            ["name" => "Tizi Nbechar", "wilaya_id" => "19"],
            ["name" => "Salah Bey", "wilaya_id" => "19"],
            ["name" => "Ain Azal", "wilaya_id" => "19"],
            ["name" => "Guenzet", "wilaya_id" => "19"],
            ["name" => "Talaifacene", "wilaya_id" => "19"],
            ["name" => "Bougaa", "wilaya_id" => "19"],
            ["name" => "Beni Fouda", "wilaya_id" => "19"],
            ["name" => "Tachouda", "wilaya_id" => "19"],
            ["name" => "Beni Mouhli", "wilaya_id" => "19"],
            ["name" => "Ouled Sabor", "wilaya_id" => "19"],
            ["name" => "Guellal", "wilaya_id" => "19"],
            ["name" => "Ain Sebt", "wilaya_id" => "19"],
            ["name" => "Hammam Guergour", "wilaya_id" => "19"],
            ["name" => "Ait Naoual Mezada", "wilaya_id" => "19"],
            ["name" => "Ksar El Abtal", "wilaya_id" => "19"],
            ["name" => "Beni Hocine", "wilaya_id" => "19"],
            ["name" => "Ait Tizi", "wilaya_id" => "19"],
            ["name" => "Maouklane", "wilaya_id" => "19"],
            ["name" => "Guelta Zerka", "wilaya_id" => "19"],
            ["name" => "Oued El Barad", "wilaya_id" => "19"],
            ["name" => "Taya", "wilaya_id" => "19"],
            ["name" => "El Ouldja", "wilaya_id" => "19"],
            ["name" => "Tella", "wilaya_id" => "19"],
            ["name" => "Saida", "wilaya_id" => "20"],
            ["name" => "Doui Thabet", "wilaya_id" => "20"],
            ["name" => "Ain El Hadjar", "wilaya_id" => "20"],
            ["name" => "Ouled Khaled", "wilaya_id" => "20"],
            ["name" => "Moulay Larbi", "wilaya_id" => "20"],
            ["name" => "Youb", "wilaya_id" => "20"],
            ["name" => "Hounet", "wilaya_id" => "20"],
            ["name" => "Sidi Amar", "wilaya_id" => "20"],
            ["name" => "Sidi Boubekeur", "wilaya_id" => "20"],
            ["name" => "El Hassasna", "wilaya_id" => "20"],
            ["name" => "Maamora", "wilaya_id" => "20"],
            ["name" => "Sidi Ahmed", "wilaya_id" => "20"],
            ["name" => "Ain Sekhouna", "wilaya_id" => "20"],
            ["name" => "Ouled Brahim", "wilaya_id" => "20"],
            ["name" => "Tircine", "wilaya_id" => "20"],
            ["name" => "Ain Soltane", "wilaya_id" => "20"],
            ["name" => "Skikda", "wilaya_id" => "21"],
            ["name" => "Ain Zouit", "wilaya_id" => "21"],
            ["name" => "El Hadaik", "wilaya_id" => "21"],
            ["name" => "Azzaba", "wilaya_id" => "21"],
            ["name" => "Djendel Saadi Mohamed", "wilaya_id" => "21"],
            ["name" => "Ain Cherchar", "wilaya_id" => "21"],
            ["name" => "Bekkouche Lakhdar", "wilaya_id" => "21"],
            ["name" => "Benazouz", "wilaya_id" => "21"],
            ["name" => "Es Sebt", "wilaya_id" => "21"],
            ["name" => "Collo", "wilaya_id" => "21"],
            ["name" => "Beni Zid", "wilaya_id" => "21"],
            ["name" => "Kerkera", "wilaya_id" => "21"],
            ["name" => "Ouled Attia", "wilaya_id" => "21"],
            ["name" => "Oued Zehour", "wilaya_id" => "21"],
            ["name" => "Zitouna", "wilaya_id" => "21"],
            ["name" => "El Harrouch", "wilaya_id" => "21"],
            ["name" => "Zerdazas", "wilaya_id" => "21"],
            ["name" => "Ouled Hebaba", "wilaya_id" => "21"],
            ["name" => "Sidi Mezghiche", "wilaya_id" => "21"],
            ["name" => "Emdjez Edchich", "wilaya_id" => "21"],
            ["name" => "Beni Oulbane", "wilaya_id" => "21"],
            ["name" => "Ain Bouziane", "wilaya_id" => "21"],
            ["name" => "Ramdane Djamel", "wilaya_id" => "21"],
            ["name" => "Beni Bachir", "wilaya_id" => "21"],
            ["name" => "Salah Bouchaour", "wilaya_id" => "21"],
            ["name" => "Tamalous", "wilaya_id" => "21"],
            ["name" => "Ain Kechra", "wilaya_id" => "21"],
            ["name" => "Oum Toub", "wilaya_id" => "21"],
            ["name" => "Bein El Ouiden", "wilaya_id" => "21"],
            ["name" => "Fil Fila", "wilaya_id" => "21"],
            ["name" => "Cheraia", "wilaya_id" => "21"],
            ["name" => "Kanoua", "wilaya_id" => "21"],
            ["name" => "El Ghedir", "wilaya_id" => "21"],
            ["name" => "Bouchtata", "wilaya_id" => "21"],
            ["name" => "Ouldja Boulbalout", "wilaya_id" => "21"],
            ["name" => "Kheneg Mayoum", "wilaya_id" => "21"],
            ["name" => "Hamadi Krouma", "wilaya_id" => "21"],
            ["name" => "El Marsa", "wilaya_id" => "21"],
            ["name" => "Sidi Bel Abbes", "wilaya_id" => "22"],
            ["name" => "Tessala", "wilaya_id" => "22"],
            ["name" => "Sidi Brahim", "wilaya_id" => "22"],
            ["name" => "Mostefa Ben Brahim", "wilaya_id" => "22"],
            ["name" => "Telagh", "wilaya_id" => "22"],
            ["name" => "Mezaourou", "wilaya_id" => "22"],
            ["name" => "Boukhanafis", "wilaya_id" => "22"],
            ["name" => "Sidi Ali Boussidi", "wilaya_id" => "22"],
            ["name" => "Badredine El Mokrani", "wilaya_id" => "22"],
            ["name" => "Marhoum", "wilaya_id" => "22"],
            ["name" => "Tafissour", "wilaya_id" => "22"],
            ["name" => "Amarnas", "wilaya_id" => "22"],
            ["name" => "Tilmouni", "wilaya_id" => "22"],
            ["name" => "Sidi Lahcene", "wilaya_id" => "22"],
            ["name" => "Ain Thrid", "wilaya_id" => "22"],
            ["name" => "Makedra", "wilaya_id" => "22"],
            ["name" => "Tenira", "wilaya_id" => "22"],
            ["name" => "Moulay Slissen", "wilaya_id" => "22"],
            ["name" => "El Hacaiba", "wilaya_id" => "22"],
            ["name" => "Hassi Zehana", "wilaya_id" => "22"],
            ["name" => "Tabia", "wilaya_id" => "22"],
            ["name" => "Merine", "wilaya_id" => "22"],
            ["name" => "Ras El Ma", "wilaya_id" => "22"],
            ["name" => "Ain Tindamine", "wilaya_id" => "22"],
            ["name" => "Ain Kada", "wilaya_id" => "22"],
            ["name" => "Mcid", "wilaya_id" => "22"],
            ["name" => "Sidi Khaled", "wilaya_id" => "22"],
            ["name" => "Ain El Berd", "wilaya_id" => "22"],
            ["name" => "Sfissef", "wilaya_id" => "22"],
            ["name" => "Ain Adden", "wilaya_id" => "22"],
            ["name" => "Oued Taourira", "wilaya_id" => "22"],
            ["name" => "Dhaya", "wilaya_id" => "22"],
            ["name" => "Zerouala", "wilaya_id" => "22"],
            ["name" => "Lamtar", "wilaya_id" => "22"],
            ["name" => "Sidi Chaib", "wilaya_id" => "22"],
            ["name" => "Sidi Dahou Dezairs", "wilaya_id" => "22"],
            ["name" => "Oued Sbaa", "wilaya_id" => "22"],
            ["name" => "Boudjebaa El Bordj", "wilaya_id" => "22"],
            ["name" => "Sehala Thaoura", "wilaya_id" => "22"],
            ["name" => "Sidi Yacoub", "wilaya_id" => "22"],
            ["name" => "Sidi Hamadouche", "wilaya_id" => "22"],
            ["name" => "Belarbi", "wilaya_id" => "22"],
            ["name" => "Oued Sefioun", "wilaya_id" => "22"],
            ["name" => "Teghalimet", "wilaya_id" => "22"],
            ["name" => "Ben Badis", "wilaya_id" => "22"],
            ["name" => "Sidi Ali Benyoub", "wilaya_id" => "22"],
            ["name" => "Chetouane Belaila", "wilaya_id" => "22"],
            ["name" => "Bir El Hammam", "wilaya_id" => "22"],
            ["name" => "Taoudmout", "wilaya_id" => "22"],
            ["name" => "Redjem Demouche", "wilaya_id" => "22"],
            ["name" => "Benachiba Chelia", "wilaya_id" => "22"],
            ["name" => "Hassi Dahou", "wilaya_id" => "22"],
            ["name" => "Annaba", "wilaya_id" => "23"],
            ["name" => "Berrahel", "wilaya_id" => "23"],
            ["name" => "El Hadjar", "wilaya_id" => "23"],
            ["name" => "Eulma", "wilaya_id" => "23"],
            ["name" => "El Bouni", "wilaya_id" => "23"],
            ["name" => "Oued El Aneb", "wilaya_id" => "23"],
            ["name" => "Cheurfa", "wilaya_id" => "23"],
            ["name" => "Seraidi", "wilaya_id" => "23"],
            ["name" => "Ain Berda", "wilaya_id" => "23"],
            ["name" => "Chetaibi", "wilaya_id" => "23"],
            ["name" => "Sidi Amer", "wilaya_id" => "23"],
            ["name" => "Treat", "wilaya_id" => "23"],
            ["name" => "Guelma", "wilaya_id" => "24"],
            ["name" => "Nechmaya", "wilaya_id" => "24"],
            ["name" => "Bouati Mahmoud", "wilaya_id" => "24"],
            ["name" => "Oued Zenati", "wilaya_id" => "24"],
            ["name" => "Tamlouka", "wilaya_id" => "24"],
            ["name" => "Oued Fragha", "wilaya_id" => "24"],
            ["name" => "Ain Sandel", "wilaya_id" => "24"],
            ["name" => "Ras El Agba", "wilaya_id" => "24"],
            ["name" => "Dahouara", "wilaya_id" => "24"],
            ["name" => "Belkhir", "wilaya_id" => "24"],
            ["name" => "Ben Djarah", "wilaya_id" => "24"],
            ["name" => "Bou Hamdane", "wilaya_id" => "24"],
            ["name" => "Ain Makhlouf", "wilaya_id" => "24"],
            ["name" => "Ain Ben Beida", "wilaya_id" => "24"],
            ["name" => "Khezara", "wilaya_id" => "24"],
            ["name" => "Beni Mezline", "wilaya_id" => "24"],
            ["name" => "Bou Hachana", "wilaya_id" => "24"],
            ["name" => "Guelaat Bou Sbaa", "wilaya_id" => "24"],
            ["name" => "Hammam Maskhoutine", "wilaya_id" => "24"],
            ["name" => "El Fedjoudj", "wilaya_id" => "24"],
            ["name" => "Bordj Sabat", "wilaya_id" => "24"],
            ["name" => "Hamman Nbail", "wilaya_id" => "24"],
            ["name" => "Ain Larbi", "wilaya_id" => "24"],
            ["name" => "Medjez Amar", "wilaya_id" => "24"],
            ["name" => "Bouchegouf", "wilaya_id" => "24"],
            ["name" => "Heliopolis", "wilaya_id" => "24"],
            ["name" => "Ain Hessania", "wilaya_id" => "24"],
            ["name" => "Roknia", "wilaya_id" => "24"],
            ["name" => "Salaoua Announa", "wilaya_id" => "24"],
            ["name" => "Medjez Sfa", "wilaya_id" => "24"],
            ["name" => "Boumahra Ahmed", "wilaya_id" => "24"],
            ["name" => "Ain Reggada", "wilaya_id" => "24"],
            ["name" => "Oued Cheham", "wilaya_id" => "24"],
            ["name" => "Djeballah Khemissi", "wilaya_id" => "24"],
            ["name" => "Constantine", "wilaya_id" => "25"],
            ["name" => "Hamma Bouziane", "wilaya_id" => "25"],
            ["name" => "El Haria", "wilaya_id" => "25"],
            ["name" => "Zighoud Youcef", "wilaya_id" => "25"],
            ["name" => "Didouche Mourad", "wilaya_id" => "25"],
            ["name" => "El Khroub", "wilaya_id" => "25"],
            ["name" => "Ain Abid", "wilaya_id" => "25"],
            ["name" => "Beni Hamiden", "wilaya_id" => "25"],
            ["name" => "Ouled Rahmoune", "wilaya_id" => "25"],
            ["name" => "Ain Smara", "wilaya_id" => "25"],
            ["name" => "Mesaoud Boudjeriou", "wilaya_id" => "25"],
            ["name" => "Ibn Ziad", "wilaya_id" => "25"],
            ["name" => "Medea", "wilaya_id" => "26"],
            ["name" => "Ouzera", "wilaya_id" => "26"],
            ["name" => "Ouled Maaref", "wilaya_id" => "26"],
            ["name" => "Ain Boucif", "wilaya_id" => "26"],
            ["name" => "Aissaouia", "wilaya_id" => "26"],
            ["name" => "Ouled Deide", "wilaya_id" => "26"],
            ["name" => "El Omaria", "wilaya_id" => "26"],
            ["name" => "Derrag", "wilaya_id" => "26"],
            ["name" => "El Guelbelkebir", "wilaya_id" => "26"],
            ["name" => "Bouaiche", "wilaya_id" => "26"],
            ["name" => "Mezerena", "wilaya_id" => "26"],
            ["name" => "Ouled Brahim", "wilaya_id" => "26"],
            ["name" => "Damiat", "wilaya_id" => "26"],
            ["name" => "Sidi Ziane", "wilaya_id" => "26"],
            ["name" => "Tamesguida", "wilaya_id" => "26"],
            ["name" => "El Hamdania", "wilaya_id" => "26"],
            ["name" => "Kef Lakhdar", "wilaya_id" => "26"],
            ["name" => "Chelalet El Adhaoura", "wilaya_id" => "26"],
            ["name" => "Bouskene", "wilaya_id" => "26"],
            ["name" => "Rebaia", "wilaya_id" => "26"],
            ["name" => "Bouchrahil", "wilaya_id" => "26"],
            ["name" => "Ouled Hellal", "wilaya_id" => "26"],
            ["name" => "Tafraout", "wilaya_id" => "26"],
            ["name" => "Baata", "wilaya_id" => "26"],
            ["name" => "Boghar", "wilaya_id" => "26"],
            ["name" => "Sidi Naamane", "wilaya_id" => "26"],
            ["name" => "Ouled Bouachra", "wilaya_id" => "26"],
            ["name" => "Sidi Zahar", "wilaya_id" => "26"],
            ["name" => "Oued Harbil", "wilaya_id" => "26"],
            ["name" => "Benchicao", "wilaya_id" => "26"],
            ["name" => "Sidi Damed", "wilaya_id" => "26"],
            ["name" => "Aziz", "wilaya_id" => "26"],
            ["name" => "Souagui", "wilaya_id" => "26"],
            ["name" => "Zoubiria", "wilaya_id" => "26"],
            ["name" => "Ksar El Boukhari", "wilaya_id" => "26"],
            ["name" => "El Azizia", "wilaya_id" => "26"],
            ["name" => "Djouab", "wilaya_id" => "26"],
            ["name" => "Chahbounia", "wilaya_id" => "26"],
            ["name" => "Meghraoua", "wilaya_id" => "26"],
            ["name" => "Cheniguel", "wilaya_id" => "26"],
            ["name" => "Ain Ouksir", "wilaya_id" => "26"],
            ["name" => "Oum El Djalil", "wilaya_id" => "26"],
            ["name" => "Ouamri", "wilaya_id" => "26"],
            ["name" => "Si Mahdjoub", "wilaya_id" => "26"],
            ["name" => "Tlatet Eddoair", "wilaya_id" => "26"],
            ["name" => "Beni Slimane", "wilaya_id" => "26"],
            ["name" => "Berrouaghia", "wilaya_id" => "26"],
            ["name" => "Seghouane", "wilaya_id" => "26"],
            ["name" => "Meftaha", "wilaya_id" => "26"],
            ["name" => "Mihoub", "wilaya_id" => "26"],
            ["name" => "Boughezoul", "wilaya_id" => "26"],
            ["name" => "Tablat", "wilaya_id" => "26"],
            ["name" => "Deux Bassins", "wilaya_id" => "26"],
            ["name" => "Draa Essamar", "wilaya_id" => "26"],
            ["name" => "Sidi Errabia", "wilaya_id" => "26"],
            ["name" => "Bir Ben Laabed", "wilaya_id" => "26"],
            ["name" => "El Ouinet", "wilaya_id" => "26"],
            ["name" => "Ouled Antar", "wilaya_id" => "26"],
            ["name" => "Bouaichoune", "wilaya_id" => "26"],
            ["name" => "Hannacha", "wilaya_id" => "26"],
            ["name" => "Sedraia", "wilaya_id" => "26"],
            ["name" => "Medjebar", "wilaya_id" => "26"],
            ["name" => "Khams Djouamaa", "wilaya_id" => "26"],
            ["name" => "Saneg", "wilaya_id" => "26"],
            ["name" => "Mostaganem", "wilaya_id" => "27"],
            ["name" => "Sayada", "wilaya_id" => "27"],
            ["name" => "Fornaka", "wilaya_id" => "27"],
            ["name" => "Stidia", "wilaya_id" => "27"],
            ["name" => "Ain Nouissy", "wilaya_id" => "27"],
            ["name" => "Hassi Maameche", "wilaya_id" => "27"],
            ["name" => "Ain Tadles", "wilaya_id" => "27"],
            ["name" => "Sour", "wilaya_id" => "27"],
            ["name" => "Oued El Kheir", "wilaya_id" => "27"],
            ["name" => "Sidi Bellater", "wilaya_id" => "27"],
            ["name" => "KheiredineÂ ", "wilaya_id" => "27"],
            ["name" => "Sidi Ali", "wilaya_id" => "27"],
            ["name" => "Abdelmalek Ramdane", "wilaya_id" => "27"],
            ["name" => "Hadjadj", "wilaya_id" => "27"],
            ["name" => "Nekmaria", "wilaya_id" => "27"],
            ["name" => "Sidi Lakhdar", "wilaya_id" => "27"],
            ["name" => "Achaacha", "wilaya_id" => "27"],
            ["name" => "Khadra", "wilaya_id" => "27"],
            ["name" => "Bouguirat", "wilaya_id" => "27"],
            ["name" => "Sirat", "wilaya_id" => "27"],
            ["name" => "Ain Sidi Cherif", "wilaya_id" => "27"],
            ["name" => "Mesra", "wilaya_id" => "27"],
            ["name" => "Mansourah", "wilaya_id" => "27"],
            ["name" => "Souaflia", "wilaya_id" => "27"],
            ["name" => "Ouled Boughalem", "wilaya_id" => "27"],
            ["name" => "Ouled Maallah", "wilaya_id" => "27"],
            ["name" => "Mezghrane", "wilaya_id" => "27"],
            ["name" => "Ain Boudinar", "wilaya_id" => "27"],
            ["name" => "Tazgait", "wilaya_id" => "27"],
            ["name" => "Safsaf", "wilaya_id" => "27"],
            ["name" => "Touahria", "wilaya_id" => "27"],
            ["name" => "El Hassiane", "wilaya_id" => "27"],
            ["name" => "Msila", "wilaya_id" => "28"],
            ["name" => "Maadid", "wilaya_id" => "28"],
            ["name" => "Hammam Dhalaa", "wilaya_id" => "28"],
            ["name" => "Ouled Derradj", "wilaya_id" => "28"],
            ["name" => "Tarmount", "wilaya_id" => "28"],
            ["name" => "Mtarfa", "wilaya_id" => "28"],
            ["name" => "Khoubana", "wilaya_id" => "28"],
            ["name" => "Mcif", "wilaya_id" => "28"],
            ["name" => "Chellal", "wilaya_id" => "28"],
            ["name" => "Ouled Madhi", "wilaya_id" => "28"],
            ["name" => "Magra", "wilaya_id" => "28"],
            ["name" => "Berhoum", "wilaya_id" => "28"],
            ["name" => "Ain Khadra", "wilaya_id" => "28"],
            ["name" => "Ouled Addi Guebala", "wilaya_id" => "28"],
            ["name" => "Belaiba", "wilaya_id" => "28"],
            ["name" => "Sidi Aissa", "wilaya_id" => "28"],
            ["name" => "Ain El Hadjel", "wilaya_id" => "28"],
            ["name" => "Sidi Hadjeres", "wilaya_id" => "28"],
            ["name" => "Ouanougha", "wilaya_id" => "28"],
            ["name" => "Bou Saada", "wilaya_id" => "28"],
            ["name" => "Ouled Sidi Brahim", "wilaya_id" => "28"],
            ["name" => "Sidi Ameur", "wilaya_id" => "28"],
            ["name" => "Tamsa", "wilaya_id" => "28"],
            ["name" => "Ben Srour", "wilaya_id" => "28"],
            ["name" => "Ouled Slimane", "wilaya_id" => "28"],
            ["name" => "El Houamed", "wilaya_id" => "28"],
            ["name" => "El Hamel", "wilaya_id" => "28"],
            ["name" => "Ouled Mansour", "wilaya_id" => "28"],
            ["name" => "Maarif", "wilaya_id" => "28"],
            ["name" => "Dehahna", "wilaya_id" => "28"],
            ["name" => "Bouti Sayah", "wilaya_id" => "28"],
            ["name" => "Khettouti Sed Djir", "wilaya_id" => "28"],
            ["name" => "Zarzour", "wilaya_id" => "28"],
            ["name" => "Oued Chair", "wilaya_id" => "28"],
            ["name" => "Benzouh", "wilaya_id" => "28"],
            ["name" => "Bir Foda", "wilaya_id" => "28"],
            ["name" => "Ain Fares", "wilaya_id" => "28"],
            ["name" => "Sidi Mhamed", "wilaya_id" => "28"],
            ["name" => "Ouled Atia", "wilaya_id" => "28"],
            ["name" => "Souamaa", "wilaya_id" => "28"],
            ["name" => "Ain El Melh", "wilaya_id" => "28"],
            ["name" => "Medjedel", "wilaya_id" => "28"],
            ["name" => "Slim", "wilaya_id" => "28"],
            ["name" => "Ain Errich", "wilaya_id" => "28"],
            ["name" => "Beni Ilmane", "wilaya_id" => "28"],
            ["name" => "Oultene", "wilaya_id" => "28"],
            ["name" => "Djebel Messaad", "wilaya_id" => "28"],
            ["name" => "Mascara", "wilaya_id" => "29"],
            ["name" => "Bou Hanifia", "wilaya_id" => "29"],
            ["name" => "Tizi", "wilaya_id" => "29"],
            ["name" => "Hacine", "wilaya_id" => "29"],
            ["name" => "Maoussa", "wilaya_id" => "29"],
            ["name" => "Teghennif", "wilaya_id" => "29"],
            ["name" => "El Hachem", "wilaya_id" => "29"],
            ["name" => "Sidi Kada", "wilaya_id" => "29"],
            ["name" => "Zelmata", "wilaya_id" => "29"],
            ["name" => "Oued El Abtal", "wilaya_id" => "29"],
            ["name" => "Ain Ferah", "wilaya_id" => "29"],
            ["name" => "Ghriss", "wilaya_id" => "29"],
            ["name" => "Froha", "wilaya_id" => "29"],
            ["name" => "Matemore", "wilaya_id" => "29"],
            ["name" => "Makdha", "wilaya_id" => "29"],
            ["name" => "Sidi Boussaid", "wilaya_id" => "29"],
            ["name" => "El Bordj", "wilaya_id" => "29"],
            ["name" => "Ain Fekan", "wilaya_id" => "29"],
            ["name" => "Benian", "wilaya_id" => "29"],
            ["name" => "Khalouia", "wilaya_id" => "29"],
            ["name" => "El Menaouer", "wilaya_id" => "29"],
            ["name" => "Oued Taria", "wilaya_id" => "29"],
            ["name" => "Aouf", "wilaya_id" => "29"],
            ["name" => "Ain Fares", "wilaya_id" => "29"],
            ["name" => "Ain Frass", "wilaya_id" => "29"],
            ["name" => "Sig", "wilaya_id" => "29"],
            ["name" => "Oggaz", "wilaya_id" => "29"],
            ["name" => "Alaimia", "wilaya_id" => "29"],
            ["name" => "El Gaada", "wilaya_id" => "29"],
            ["name" => "Zahana", "wilaya_id" => "29"],
            ["name" => "Mohammadia", "wilaya_id" => "29"],
            ["name" => "Sidi Abdelmoumene", "wilaya_id" => "29"],
            ["name" => "Ferraguig", "wilaya_id" => "29"],
            ["name" => "El Ghomri", "wilaya_id" => "29"],
            ["name" => "Sedjerara", "wilaya_id" => "29"],
            ["name" => "Moctadouz", "wilaya_id" => "29"],
            ["name" => "Bou Henni", "wilaya_id" => "29"],
            ["name" => "Guettena", "wilaya_id" => "29"],
            ["name" => "El Mamounia", "wilaya_id" => "29"],
            ["name" => "El Keurt", "wilaya_id" => "29"],
            ["name" => "Gharrous", "wilaya_id" => "29"],
            ["name" => "Gherdjoum", "wilaya_id" => "29"],
            ["name" => "Chorfa", "wilaya_id" => "29"],
            ["name" => "Ras Ain Amirouche", "wilaya_id" => "29"],
            ["name" => "Nesmot", "wilaya_id" => "29"],
            ["name" => "Sidi Abdeldjebar", "wilaya_id" => "29"],
            ["name" => "Sehailia", "wilaya_id" => "29"],
            ["name" => "Ouargla", "wilaya_id" => "30"],
            ["name" => "Ain Beida", "wilaya_id" => "30"],
            ["name" => "Ngoussa", "wilaya_id" => "30"],
            ["name" => "Hassi Messaoud", "wilaya_id" => "30"],
            ["name" => "Rouissat", "wilaya_id" => "30"],
            ["name" => "Balidat Ameur", "wilaya_id" => "30"],
            ["name" => "Tebesbest", "wilaya_id" => "30"],
            ["name" => "Nezla", "wilaya_id" => "30"],
            ["name" => "Zaouia El Abidia", "wilaya_id" => "30"],
            ["name" => "Sidi Slimane", "wilaya_id" => "30"],
            ["name" => "Sidi Khouiled", "wilaya_id" => "30"],
            ["name" => "Hassi Ben Abdellah", "wilaya_id" => "30"],
            ["name" => "Touggourt", "wilaya_id" => "30"],
            ["name" => "El Hadjira", "wilaya_id" => "30"],
            ["name" => "Taibet", "wilaya_id" => "30"],
            ["name" => "Tamacine", "wilaya_id" => "30"],
            ["name" => "Benaceur", "wilaya_id" => "30"],
            ["name" => "Mnaguer", "wilaya_id" => "30"],
            ["name" => "Megarine", "wilaya_id" => "30"],
            ["name" => "El Allia", "wilaya_id" => "30"],
            ["name" => "El Borma", "wilaya_id" => "30"],
            ["name" => "Oran", "wilaya_id" => "31"],
            ["name" => "Gdyel", "wilaya_id" => "31"],
            ["name" => "Bir El Djir", "wilaya_id" => "31"],
            ["name" => "Hassi Bounif", "wilaya_id" => "31"],
            ["name" => "Es Senia", "wilaya_id" => "31"],
            ["name" => "Arzew", "wilaya_id" => "31"],
            ["name" => "Bethioua", "wilaya_id" => "31"],
            ["name" => "Marsat El Hadjadj", "wilaya_id" => "31"],
            ["name" => "Ain Turk", "wilaya_id" => "31"],
            ["name" => "El Ancar", "wilaya_id" => "31"],
            ["name" => "Oued Tlelat", "wilaya_id" => "31"],
            ["name" => "Tafraoui", "wilaya_id" => "31"],
            ["name" => "Sidi Chami", "wilaya_id" => "31"],
            ["name" => "Boufatis", "wilaya_id" => "31"],
            ["name" => "Mers El Kebir", "wilaya_id" => "31"],
            ["name" => "Bousfer", "wilaya_id" => "31"],
            ["name" => "El Karma", "wilaya_id" => "31"],
            ["name" => "El Braya", "wilaya_id" => "31"],
            ["name" => "Hassi Ben Okba", "wilaya_id" => "31"],
            ["name" => "Ben Freha", "wilaya_id" => "31"],
            ["name" => "Hassi Mefsoukh", "wilaya_id" => "31"],
            ["name" => "Sidi Ben Yabka", "wilaya_id" => "31"],
            ["name" => "Messerghin", "wilaya_id" => "31"],
            ["name" => "Boutlelis", "wilaya_id" => "31"],
            ["name" => "Ain Kerma", "wilaya_id" => "31"],
            ["name" => "Ain Biya", "wilaya_id" => "31"],
            ["name" => "El Bayadh", "wilaya_id" => "32"],
            ["name" => "Rogassa", "wilaya_id" => "32"],
            ["name" => "Stitten", "wilaya_id" => "32"],
            ["name" => "Brezina", "wilaya_id" => "32"],
            ["name" => "Ghassoul", "wilaya_id" => "32"],
            ["name" => "Boualem", "wilaya_id" => "32"],
            ["name" => "El Abiodh Sidi Cheikh", "wilaya_id" => "32"],
            ["name" => "Ain El Orak", "wilaya_id" => "32"],
            ["name" => "Arbaouat", "wilaya_id" => "32"],
            ["name" => "Bougtoub", "wilaya_id" => "32"],
            ["name" => "El Kheither", "wilaya_id" => "32"],
            ["name" => "Kef El Ahmar", "wilaya_id" => "32"],
            ["name" => "Boussemghoun", "wilaya_id" => "32"],
            ["name" => "Chellala", "wilaya_id" => "32"],
            ["name" => "Krakda", "wilaya_id" => "32"],
            ["name" => "El Bnoud", "wilaya_id" => "32"],
            ["name" => "Cheguig", "wilaya_id" => "32"],
            ["name" => "Sidi Ameur", "wilaya_id" => "32"],
            ["name" => "El Mehara", "wilaya_id" => "32"],
            ["name" => "Tousmouline", "wilaya_id" => "32"],
            ["name" => "Sidi Slimane", "wilaya_id" => "32"],
            ["name" => "Sidi Tifour", "wilaya_id" => "32"],
            ["name" => "Illizi", "wilaya_id" => "33"],
            ["name" => "Djanet", "wilaya_id" => "33"],
            ["name" => "Debdeb", "wilaya_id" => "33"],
            ["name" => "Bordj Omar Driss", "wilaya_id" => "33"],
            ["name" => "Bordj El Haouasse", "wilaya_id" => "33"],
            ["name" => "In Amenas", "wilaya_id" => "33"],
            ["name" => "Bordj Bou Arreridj", "wilaya_id" => "34"],
            ["name" => "Ras El Oued", "wilaya_id" => "34"],
            ["name" => "Bordj Zemoura", "wilaya_id" => "34"],
            ["name" => "Mansoura", "wilaya_id" => "34"],
            ["name" => "El Mhir", "wilaya_id" => "34"],
            ["name" => "Ben Daoud", "wilaya_id" => "34"],
            ["name" => "El Achir", "wilaya_id" => "34"],
            ["name" => "Ain Taghrout", "wilaya_id" => "34"],
            ["name" => "Bordj Ghdir", "wilaya_id" => "34"],
            ["name" => "Sidi Embarek", "wilaya_id" => "34"],
            ["name" => "El Hamadia", "wilaya_id" => "34"],
            ["name" => "Belimour", "wilaya_id" => "34"],
            ["name" => "Medjana", "wilaya_id" => "34"],
            ["name" => "Teniet En Nasr", "wilaya_id" => "34"],
            ["name" => "Djaafra", "wilaya_id" => "34"],
            ["name" => "El Main", "wilaya_id" => "34"],
            ["name" => "Ouled Brahem", "wilaya_id" => "34"],
            ["name" => "Ouled Dahmane", "wilaya_id" => "34"],
            ["name" => "Hasnaoua", "wilaya_id" => "34"],
            ["name" => "Khelil", "wilaya_id" => "34"],
            ["name" => "Taglait", "wilaya_id" => "34"],
            ["name" => "Ksour", "wilaya_id" => "34"],
            ["name" => "Ouled Sidi Brahim", "wilaya_id" => "34"],
            ["name" => "Tafreg", "wilaya_id" => "34"],
            ["name" => "Colla", "wilaya_id" => "34"],
            ["name" => "Tixter", "wilaya_id" => "34"],
            ["name" => "El Ach", "wilaya_id" => "34"],
            ["name" => "El Anseur", "wilaya_id" => "34"],
            ["name" => "Tesmart", "wilaya_id" => "34"],
            ["name" => "Ain Tesra", "wilaya_id" => "34"],
            ["name" => "Bir Kasdali", "wilaya_id" => "34"],
            ["name" => "Ghilassa", "wilaya_id" => "34"],
            ["name" => "Rabta", "wilaya_id" => "34"],
            ["name" => "Haraza", "wilaya_id" => "34"],
            ["name" => "Boumerdes", "wilaya_id" => "35"],
            ["name" => "Boudouaou", "wilaya_id" => "35"],
            ["name" => "Afir", "wilaya_id" => "35"],
            ["name" => "Bordj Menaiel", "wilaya_id" => "35"],
            ["name" => "Baghlia", "wilaya_id" => "35"],
            ["name" => "Sidi Daoud", "wilaya_id" => "35"],
            ["name" => "Naciria", "wilaya_id" => "35"],
            ["name" => "Djinet", "wilaya_id" => "35"],
            ["name" => "Isser", "wilaya_id" => "35"],
            ["name" => "Zemmouri", "wilaya_id" => "35"],
            ["name" => "Si Mustapha", "wilaya_id" => "35"],
            ["name" => "Tidjelabine", "wilaya_id" => "35"],
            ["name" => "Chabet El Ameur", "wilaya_id" => "35"],
            ["name" => "Thenia", "wilaya_id" => "35"],
            ["name" => "Timezrit", "wilaya_id" => "35"],
            ["name" => "Corso", "wilaya_id" => "35"],
            ["name" => "Ouled Moussa", "wilaya_id" => "35"],
            ["name" => "Larbatache", "wilaya_id" => "35"],
            ["name" => "Bouzegza Keddara", "wilaya_id" => "35"],
            ["name" => "Taourga", "wilaya_id" => "35"],
            ["name" => "Ouled Aissa", "wilaya_id" => "35"],
            ["name" => "Ben Choud", "wilaya_id" => "35"],
            ["name" => "Dellys", "wilaya_id" => "35"],
            ["name" => "Ammal", "wilaya_id" => "35"],
            ["name" => "Beni Amrane", "wilaya_id" => "35"],
            ["name" => "Souk El Had", "wilaya_id" => "35"],
            ["name" => "Boudouaou El Bahri", "wilaya_id" => "35"],
            ["name" => "Ouled Hedadj", "wilaya_id" => "35"],
            ["name" => "Laghata", "wilaya_id" => "35"],
            ["name" => "Hammedi", "wilaya_id" => "35"],
            ["name" => "Khemis El Khechna", "wilaya_id" => "35"],
            ["name" => "El Kharrouba", "wilaya_id" => "35"],
            ["name" => "El Tarf", "wilaya_id" => "36"],
            ["name" => "Bouhadjar", "wilaya_id" => "36"],
            ["name" => "Ben Mhidi", "wilaya_id" => "36"],
            ["name" => "Bougous", "wilaya_id" => "36"],
            ["name" => "El Kala", "wilaya_id" => "36"],
            ["name" => "Ain El Assel", "wilaya_id" => "36"],
            ["name" => "El Aioun", "wilaya_id" => "36"],
            ["name" => "Bouteldja", "wilaya_id" => "36"],
            ["name" => "Souarekh", "wilaya_id" => "36"],
            ["name" => "Berrihane", "wilaya_id" => "36"],
            ["name" => "Lac Des Oiseaux", "wilaya_id" => "36"],
            ["name" => "Chefia", "wilaya_id" => "36"],
            ["name" => "Drean", "wilaya_id" => "36"],
            ["name" => "Chihani", "wilaya_id" => "36"],
            ["name" => "Chebaita Mokhtar", "wilaya_id" => "36"],
            ["name" => "Besbes", "wilaya_id" => "36"],
            ["name" => "Asfour", "wilaya_id" => "36"],
            ["name" => "Echatt", "wilaya_id" => "36"],
            ["name" => "Zerizer", "wilaya_id" => "36"],
            ["name" => "Zitouna", "wilaya_id" => "36"],
            ["name" => "Ain Kerma", "wilaya_id" => "36"],
            ["name" => "Oued Zitoun", "wilaya_id" => "36"],
            ["name" => "Hammam Beni Salah", "wilaya_id" => "36"],
            ["name" => "Raml Souk", "wilaya_id" => "36"],
            ["name" => "Tindouf", "wilaya_id" => "37"],
            ["name" => "Oum El Assel", "wilaya_id" => "37"],
            ["name" => "Tissemsilt", "wilaya_id" => "38"],
            ["name" => "Bordj Bou Naama", "wilaya_id" => "38"],
            ["name" => "Theniet El Had", "wilaya_id" => "38"],
            ["name" => "Lazharia", "wilaya_id" => "38"],
            ["name" => "Beni Chaib", "wilaya_id" => "38"],
            ["name" => "Lardjem", "wilaya_id" => "38"],
            ["name" => "Melaab", "wilaya_id" => "38"],
            ["name" => "Sidi Lantri", "wilaya_id" => "38"],
            ["name" => "Bordj El Emir Abdelkader", "wilaya_id" => "38"],
            ["name" => "Layoune", "wilaya_id" => "38"],
            ["name" => "Khemisti", "wilaya_id" => "38"],
            ["name" => "Ouled Bessem", "wilaya_id" => "38"],
            ["name" => "Ammari", "wilaya_id" => "38"],
            ["name" => "Youssoufia", "wilaya_id" => "38"],
            ["name" => "Sidi Boutouchent", "wilaya_id" => "38"],
            ["name" => "Larbaa", "wilaya_id" => "38"],
            ["name" => "Maasem", "wilaya_id" => "38"],
            ["name" => "Sidi Abed", "wilaya_id" => "38"],
            ["name" => "Tamalaht", "wilaya_id" => "38"],
            ["name" => "Sidi Slimane", "wilaya_id" => "38"],
            ["name" => "Boucaid", "wilaya_id" => "38"],
            ["name" => "Beni Lahcene", "wilaya_id" => "38"],
            ["name" => "El Oued", "wilaya_id" => "39"],
            ["name" => "Robbah", "wilaya_id" => "39"],
            ["name" => "Oued El Alenda", "wilaya_id" => "39"],
            ["name" => "Bayadha", "wilaya_id" => "39"],
            ["name" => "Nakhla", "wilaya_id" => "39"],
            ["name" => "Guemar", "wilaya_id" => "39"],
            ["name" => "Kouinine", "wilaya_id" => "39"],
            ["name" => "Reguiba", "wilaya_id" => "39"],
            ["name" => "Hamraia", "wilaya_id" => "39"],
            ["name" => "Taghzout", "wilaya_id" => "39"],
            ["name" => "Debila", "wilaya_id" => "39"],
            ["name" => "Hassani Abdelkrim", "wilaya_id" => "39"],
            ["name" => "Hassi Khelifa", "wilaya_id" => "39"],
            ["name" => "Taleb Larbi", "wilaya_id" => "39"],
            ["name" => "Douar El Ma", "wilaya_id" => "39"],
            ["name" => "Sidi Aoun", "wilaya_id" => "39"],
            ["name" => "Trifaoui", "wilaya_id" => "39"],
            ["name" => "Magrane", "wilaya_id" => "39"],
            ["name" => "Beni Guecha", "wilaya_id" => "39"],
            ["name" => "Ourmas", "wilaya_id" => "39"],
            ["name" => "Still", "wilaya_id" => "39"],
            ["name" => "Mrara", "wilaya_id" => "39"],
            ["name" => "Sidi Khellil", "wilaya_id" => "39"],
            ["name" => "Tendla", "wilaya_id" => "39"],
            ["name" => "El Ogla", "wilaya_id" => "39"],
            ["name" => "Mih Ouansa", "wilaya_id" => "39"],
            ["name" => "El Mghair", "wilaya_id" => "39"],
            ["name" => "Djamaa", "wilaya_id" => "39"],
            ["name" => "Oum Touyour", "wilaya_id" => "39"],
            ["name" => "Sidi Amrane", "wilaya_id" => "39"],
            ["name" => "Khenchela", "wilaya_id" => "40"],
            ["name" => "Mtoussa", "wilaya_id" => "40"],
            ["name" => "Kais", "wilaya_id" => "40"],
            ["name" => "Baghai", "wilaya_id" => "40"],
            ["name" => "El Hamma", "wilaya_id" => "40"],
            ["name" => "Ain Touila", "wilaya_id" => "40"],
            ["name" => "Taouzianat", "wilaya_id" => "40"],
            ["name" => "Bouhmama", "wilaya_id" => "40"],
            ["name" => "El Oueldja", "wilaya_id" => "40"],
            ["name" => "Remila", "wilaya_id" => "40"],
            ["name" => "Cherchar", "wilaya_id" => "40"],
            ["name" => "Djellal", "wilaya_id" => "40"],
            ["name" => "Babar", "wilaya_id" => "40"],
            ["name" => "Tamza", "wilaya_id" => "40"],
            ["name" => "Ensigha", "wilaya_id" => "40"],
            ["name" => "Ouled Rechache", "wilaya_id" => "40"],
            ["name" => "El Mahmal", "wilaya_id" => "40"],
            ["name" => "Msara", "wilaya_id" => "40"],
            ["name" => "Yabous", "wilaya_id" => "40"],
            ["name" => "Khirane", "wilaya_id" => "40"],
            ["name" => "Chelia", "wilaya_id" => "40"],
            ["name" => "Souk Ahras", "wilaya_id" => "41"],
            ["name" => "Sedrata", "wilaya_id" => "41"],
            ["name" => "Hanancha", "wilaya_id" => "41"],
            ["name" => "Mechroha", "wilaya_id" => "41"],
            ["name" => "Ouled Driss", "wilaya_id" => "41"],
            ["name" => "Tiffech", "wilaya_id" => "41"],
            ["name" => "Zaarouria", "wilaya_id" => "41"],
            ["name" => "Taoura", "wilaya_id" => "41"],
            ["name" => "Drea", "wilaya_id" => "41"],
            ["name" => "Haddada", "wilaya_id" => "41"],
            ["name" => "Khedara", "wilaya_id" => "41"],
            ["name" => "Merahna", "wilaya_id" => "41"],
            ["name" => "Ouled Moumen", "wilaya_id" => "41"],
            ["name" => "Bir Bouhouche", "wilaya_id" => "41"],
            ["name" => "Mdaourouche", "wilaya_id" => "41"],
            ["name" => "Oum El Adhaim", "wilaya_id" => "41"],
            ["name" => "Ain Zana", "wilaya_id" => "41"],
            ["name" => "Ain Soltane", "wilaya_id" => "41"],
            ["name" => "Quillen", "wilaya_id" => "41"],
            ["name" => "Sidi Fredj", "wilaya_id" => "41"],
            ["name" => "Safel El Ouiden", "wilaya_id" => "41"],
            ["name" => "Ragouba", "wilaya_id" => "41"],
            ["name" => "Khemissa", "wilaya_id" => "41"],
            ["name" => "Oued Keberit", "wilaya_id" => "41"],
            ["name" => "Terraguelt", "wilaya_id" => "41"],
            ["name" => "Zouabi", "wilaya_id" => "41"],
            ["name" => "Tipaza", "wilaya_id" => "42"],
            ["name" => "Menaceur", "wilaya_id" => "42"],
            ["name" => "Larhat", "wilaya_id" => "42"],
            ["name" => "Douaouda", "wilaya_id" => "42"],
            ["name" => "Bourkika", "wilaya_id" => "42"],
            ["name" => "Khemisti", "wilaya_id" => "42"],
            ["name" => "Aghabal", "wilaya_id" => "42"],
            ["name" => "Hadjout", "wilaya_id" => "42"],
            ["name" => "Sidi Amar", "wilaya_id" => "42"],
            ["name" => "Gouraya", "wilaya_id" => "42"],
            ["name" => "Nodor", "wilaya_id" => "42"],
            ["name" => "Chaiba", "wilaya_id" => "42"],
            ["name" => "Ain Tagourait", "wilaya_id" => "42"],
            ["name" => "Cherchel", "wilaya_id" => "42"],
            ["name" => "Damous", "wilaya_id" => "42"],
            ["name" => "Meurad", "wilaya_id" => "42"],
            ["name" => "Fouka", "wilaya_id" => "42"],
            ["name" => "Bou Ismail", "wilaya_id" => "42"],
            ["name" => "Ahmer El Ain", "wilaya_id" => "42"],
            ["name" => "Bou Haroun", "wilaya_id" => "42"],
            ["name" => "Sidi Ghiles", "wilaya_id" => "42"],
            ["name" => "Messelmoun", "wilaya_id" => "42"],
            ["name" => "Sidi Rached", "wilaya_id" => "42"],
            ["name" => "Kolea", "wilaya_id" => "42"],
            ["name" => "Attatba", "wilaya_id" => "42"],
            ["name" => "Sidi Semiane", "wilaya_id" => "42"],
            ["name" => "Beni Milleuk", "wilaya_id" => "42"],
            ["name" => "Hadjerat Ennous", "wilaya_id" => "42"],
            ["name" => "Mila", "wilaya_id" => "43"],
            ["name" => "Ferdjioua", "wilaya_id" => "43"],
            ["name" => "Chelghoum Laid", "wilaya_id" => "43"],
            ["name" => "Oued Athmenia", "wilaya_id" => "43"],
            ["name" => "Ain Mellouk", "wilaya_id" => "43"],
            ["name" => "Telerghma", "wilaya_id" => "43"],
            ["name" => "Oued Seguen", "wilaya_id" => "43"],
            ["name" => "Tadjenanet", "wilaya_id" => "43"],
            ["name" => "Benyahia Abderrahmane", "wilaya_id" => "43"],
            ["name" => "Oued Endja", "wilaya_id" => "43"],
            ["name" => "Ahmed Rachedi", "wilaya_id" => "43"],
            ["name" => "Ouled Khalouf", "wilaya_id" => "43"],
            ["name" => "Tiberguent", "wilaya_id" => "43"],
            ["name" => "Bouhatem", "wilaya_id" => "43"],
            ["name" => "Rouached", "wilaya_id" => "43"],
            ["name" => "Tessala Lamatai", "wilaya_id" => "43"],
            ["name" => "Grarem Gouga", "wilaya_id" => "43"],
            ["name" => "Sidi Merouane", "wilaya_id" => "43"],
            ["name" => "Tassadane Haddada", "wilaya_id" => "43"],
            ["name" => "Derradji Bousselah", "wilaya_id" => "43"],
            ["name" => "Minar Zarza", "wilaya_id" => "43"],
            ["name" => "Amira Arras", "wilaya_id" => "43"],
            ["name" => "Terrai Bainen", "wilaya_id" => "43"],
            ["name" => "Hamala", "wilaya_id" => "43"],
            ["name" => "Ain Tine", "wilaya_id" => "43"],
            ["name" => "El Mechira", "wilaya_id" => "43"],
            ["name" => "Sidi Khelifa", "wilaya_id" => "43"],
            ["name" => "Zeghaia", "wilaya_id" => "43"],
            ["name" => "Elayadi Barbes", "wilaya_id" => "43"],
            ["name" => "Ain Beida Harriche", "wilaya_id" => "43"],
            ["name" => "Yahia Beniguecha", "wilaya_id" => "43"],
            ["name" => "Chigara", "wilaya_id" => "43"],
            ["name" => "Ain Defla", "wilaya_id" => "44"],
            ["name" => "Miliana", "wilaya_id" => "44"],
            ["name" => "Boumedfaa", "wilaya_id" => "44"],
            ["name" => "Khemis Miliana", "wilaya_id" => "44"],
            ["name" => "Hammam Righa", "wilaya_id" => "44"],
            ["name" => "Arib", "wilaya_id" => "44"],
            ["name" => "Djelida", "wilaya_id" => "44"],
            ["name" => "El Amra", "wilaya_id" => "44"],
            ["name" => "Bourached", "wilaya_id" => "44"],
            ["name" => "El Attaf", "wilaya_id" => "44"],
            ["name" => "El Abadia", "wilaya_id" => "44"],
            ["name" => "Djendel", "wilaya_id" => "44"],
            ["name" => "Oued Chorfa", "wilaya_id" => "44"],
            ["name" => "Ain Lechiakh", "wilaya_id" => "44"],
            ["name" => "Oued Djemaa", "wilaya_id" => "44"],
            ["name" => "Rouina", "wilaya_id" => "44"],
            ["name" => "Zeddine", "wilaya_id" => "44"],
            ["name" => "El Hassania", "wilaya_id" => "44"],
            ["name" => "Bir Ouled Khelifa", "wilaya_id" => "44"],
            ["name" => "Ain Soltane", "wilaya_id" => "44"],
            ["name" => "Tarik Ibn Ziad", "wilaya_id" => "44"],
            ["name" => "Bordj Emir Khaled", "wilaya_id" => "44"],
            ["name" => "Ain Torki", "wilaya_id" => "44"],
            ["name" => "Sidi Lakhdar", "wilaya_id" => "44"],
            ["name" => "Ben Allal", "wilaya_id" => "44"],
            ["name" => "Ain Benian", "wilaya_id" => "44"],
            ["name" => "Hoceinia", "wilaya_id" => "44"],
            ["name" => "Barbouche", "wilaya_id" => "44"],
            ["name" => "Djemaa Ouled Chikh", "wilaya_id" => "44"],
            ["name" => "Mekhatria", "wilaya_id" => "44"],
            ["name" => "Bathia", "wilaya_id" => "44"],
            ["name" => "Tachta Zegagha", "wilaya_id" => "44"],
            ["name" => "Ain Bouyahia", "wilaya_id" => "44"],
            ["name" => "El Maine", "wilaya_id" => "44"],
            ["name" => "Tiberkanine", "wilaya_id" => "44"],
            ["name" => "Belaas", "wilaya_id" => "44"],
            ["name" => "Naama", "wilaya_id" => "45"],
            ["name" => "Mechria", "wilaya_id" => "45"],
            ["name" => "Ain Sefra", "wilaya_id" => "45"],
            ["name" => "Tiout", "wilaya_id" => "45"],
            ["name" => "Sfissifa", "wilaya_id" => "45"],
            ["name" => "Moghrar", "wilaya_id" => "45"],
            ["name" => "Assela", "wilaya_id" => "45"],
            ["name" => "Djeniane Bourzeg", "wilaya_id" => "45"],
            ["name" => "Ain Ben Khelil", "wilaya_id" => "45"],
            ["name" => "Makman Ben Amer", "wilaya_id" => "45"],
            ["name" => "Kasdir", "wilaya_id" => "45"],
            ["name" => "El Biod", "wilaya_id" => "45"],
            ["name" => "Ain Temouchent", "wilaya_id" => "46"],
            ["name" => "Chaabet El Ham", "wilaya_id" => "46"],
            ["name" => "Ain Kihal", "wilaya_id" => "46"],
            ["name" => "Hammam Bouhadjar", "wilaya_id" => "46"],
            ["name" => "Bou Zedjar", "wilaya_id" => "46"],
            ["name" => "Oued Berkeche", "wilaya_id" => "46"],
            ["name" => "Aghlal", "wilaya_id" => "46"],
            ["name" => "Terga", "wilaya_id" => "46"],
            ["name" => "Ain El Arbaa", "wilaya_id" => "46"],
            ["name" => "Tamzoura", "wilaya_id" => "46"],
            ["name" => "Chentouf", "wilaya_id" => "46"],
            ["name" => "Sidi Ben Adda", "wilaya_id" => "46"],
            ["name" => "Aoubellil", "wilaya_id" => "46"],
            ["name" => "El Malah", "wilaya_id" => "46"],
            ["name" => "Sidi Boumediene", "wilaya_id" => "46"],
            ["name" => "Oued Sabah", "wilaya_id" => "46"],
            ["name" => "Ouled Boudjemaa", "wilaya_id" => "46"],
            ["name" => "Ain Tolba", "wilaya_id" => "46"],
            ["name" => "El Amria", "wilaya_id" => "46"],
            ["name" => "Hassi El Ghella", "wilaya_id" => "46"],
            ["name" => "Hassasna", "wilaya_id" => "46"],
            ["name" => "Ouled Kihal", "wilaya_id" => "46"],
            ["name" => "Beni Saf", "wilaya_id" => "46"],
            ["name" => "Sidi Safi", "wilaya_id" => "46"],
            ["name" => "Oulhaca El Gheraba", "wilaya_id" => "46"],
            ["name" => "Tadmaya", "wilaya_id" => "46"],
            ["name" => "El Emir Abdelkader", "wilaya_id" => "46"],
            ["name" => "El Messaid", "wilaya_id" => "46"],
            ["name" => "Ghardaia", "wilaya_id" => "47"],
            ["name" => "El Meniaa", "wilaya_id" => "47"],
            ["name" => "Dhayet Bendhahoua", "wilaya_id" => "47"],
            ["name" => "Berriane", "wilaya_id" => "47"],
            ["name" => "Metlili", "wilaya_id" => "47"],
            ["name" => "El Guerrara", "wilaya_id" => "47"],
            ["name" => "El Atteuf", "wilaya_id" => "47"],
            ["name" => "Zelfana", "wilaya_id" => "47"],
            ["name" => "Sebseb", "wilaya_id" => "47"],
            ["name" => "Bounoura", "wilaya_id" => "47"],
            ["name" => "Hassi Fehal", "wilaya_id" => "47"],
            ["name" => "Hassi Gara", "wilaya_id" => "47"],
            ["name" => "Mansoura", "wilaya_id" => "47"],
            ["name" => "Relizane", "wilaya_id" => "48"],
            ["name" => "Oued Rhiou", "wilaya_id" => "48"],
            ["name" => "Belaassel Bouzegza", "wilaya_id" => "48"],
            ["name" => "Sidi Saada", "wilaya_id" => "48"],
            ["name" => "Ouled Aiche", "wilaya_id" => "48"],
            ["name" => "Sidi Lazreg", "wilaya_id" => "48"],
            ["name" => "El Hamadna", "wilaya_id" => "48"],
            ["name" => "Sidi Mhamed Ben Ali", "wilaya_id" => "48"],
            ["name" => "Mediouna", "wilaya_id" => "48"],
            ["name" => "Sidi Khettab", "wilaya_id" => "48"],
            ["name" => "Ammi Moussa", "wilaya_id" => "48"],
            ["name" => "Zemmoura", "wilaya_id" => "48"],
            ["name" => "Beni Dergoun", "wilaya_id" => "48"],
            ["name" => "Djidiouia", "wilaya_id" => "48"],
            ["name" => "El Guettar", "wilaya_id" => "48"],
            ["name" => "Hamri", "wilaya_id" => "48"],
            ["name" => "El Matmar", "wilaya_id" => "48"],
            ["name" => "Sidi Mhamed Ben Aouda", "wilaya_id" => "48"],
            ["name" => "Ain Tarek", "wilaya_id" => "48"],
            ["name" => "Oued Essalem", "wilaya_id" => "48"],
            ["name" => "Ouarizane", "wilaya_id" => "48"],
            ["name" => "Mazouna", "wilaya_id" => "48"],
            ["name" => "Kalaa", "wilaya_id" => "48"],
            ["name" => "Ain Rahma", "wilaya_id" => "48"],
            ["name" => "Yellel", "wilaya_id" => "48"],
            ["name" => "Oued El Djemaa", "wilaya_id" => "48"],
            ["name" => "Ramka", "wilaya_id" => "48"],
            ["name" => "Mendes", "wilaya_id" => "48"],
            ["name" => "Lahlef", "wilaya_id" => "48"],
            ["name" => "Beni Zentis", "wilaya_id" => "48"],
            ["name" => "Souk El Haad", "wilaya_id" => "48"],
            ["name" => "Dar Ben Abdellah", "wilaya_id" => "48"],
            ["name" => "El Hassi", "wilaya_id" => "48"],
            ["name" => "Had Echkalla", "wilaya_id" => "48"],
            ["name" => "Bendaoud", "wilaya_id" => "48"],
            ["name" => "El Ouldja", "wilaya_id" => "48"],
            ["name" => "Merdja Sidi Abed", "wilaya_id" => "48"],
            ["name" => "Ouled Sidi Mihoub", "wilaya_id" => "48"],
        ];

        foreach ($communes as $commune){
            Commune::create($commune);
        }
    }
}
